add settings -> Excluded Domains component
bitwarden/browser pull request #1376
Opened 2020-09-07 11:34 UTC by eliykat

## What

- **Feature name**: Ability to manage Excluded Domains
- **Description**: Adds an "Excluded Domains" screen in the Settings tab. This allows users to add and remove “Excluded Domains”, which are domains that Bitwarden will not offer to save the password for. 
- **Community Forums link:** see [here](https://community.bitwarden.com/t/ability-to-manage-excluded-domains/14194) for previous discussion.

## Screenshots and UI
Located in the Settings tab:

![Excluded domains 1](https://user-images.githubusercontent.com/31796059/92382449-f39bb600-f14f-11ea-89ef-bcf7bcd60916.PNG)

It uses the familiar URI list from the item edit screen. It includes an optional dropdown list to select from currently open domains:

![Excluded domains 22](https://user-images.githubusercontent.com/31796059/92382679-58571080-f150-11ea-8e69-6d0268c2c5e8.PNG)

It raises an error if the user tries to save with an invalid domain:

![Excluded domains 3](https://user-images.githubusercontent.com/31796059/92382725-6d33a400-f150-11ea-8515-85457b210200.PNG)

If the user enters a URI that includes a path or other information, only the domain portion of the URI will be saved. For example, "https://github.com/bitwarden/browser" is  saved as "github.com". This is intended to meet the expectation/assumption that these are domain names only (i.e. notificationBar.ts expects an exact match against window.location.hostname in the current tab).

2020-12-15 22:16 UTC, cscharf reviewed
Left some feedback, comments and general formatting stuff; thanks!

2020-12-15 22:16 UTC, cscharf commented on src/popup/app.module.ts
> +import { ExcludedDomainsComponent } from './settings/excluded-domains.component';
Same, be sure your import statements are in alphabetical order (based on from path); otherwise linter would fail.

2020-12-15 22:16 UTC, cscharf commented on src/popup/settings/excluded-domains.component.ts
> +import { PlatformUtilsService } from 'jslib/abstractions/platformUtils.service';
Please ensure the import block is in proper alpha order based on from path. should then logically and naturally group by similar constructors (abstractions, enums, services, etc.)

2020-12-15 22:16 UTC, cscharf commented on src/popup/settings/excluded-domains.component.ts
> +    OnDestroy
Import should be in alphabetical order as well

2021-01-13 09:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/browser?pullRequest=1376) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/browser?pullRequest=1376) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: eliykat<br/>:x: Thomas Rittson<br/><hr/>**Thomas Rittson** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/browser?pullRequest=1376) it.</sub>

2021-01-13 15:40 UTC, kspearrin requested changes

2021-01-13 15:40 UTC, kspearrin commented on src/_locales/en/messages.json
> +    "message": " is not a valid domain"
You need to use a placeholder value. Reference some other strings in here to see how that is done.

2021-01-13 15:40 UTC, kspearrin commented on src/popup/settings/excluded-domains.component.ts
> +                        '\'' + domain.uri + '\'' + this.i18nService.t('excludedDomainsInvalidDomain'));
string placeholder would be applied here too

2021-01-13 15:40 UTC, kspearrin commented on src/popup/settings/excluded-domains.component.ts
> +        this.loadCurrentUris();
await?

2021-01-13 15:40 UTC, kspearrin commented on src/popup/settings/excluded-domains.component.ts
> +                        this.loadCurrentUrisTimeout = window.setTimeout(() => this.loadCurrentUris(), 500);
await?

2021-01-14 08:24 UTC, eliykat commented
I think this should all be addressed now.

With placeholders in `messages.json`, is the `example` string consumed by the code anywhere, or is it effectively a comment?

2021-01-14 15:13 UTC, kspearrin commented
> With placeholders in `messages.json`, is the `example` string consumed by the code anywhere, or is it effectively a comment?

It's just a comment/hint for the translators to gain more context. Not used in code.

2021-01-14 15:13 UTC, kspearrin approved these changes

2021-01-25 20:25 UTC, merged