Browser <-> desktop communication
bitwarden/browser pull request #1426
Opened 2020-10-11 18:54 UTC by Hinton

This is an initial PoC for the browser <-> desktop communication, with the goal to enable biometric unlock.

Currently enabling and unlocking works in Chrome as long as the focus of the popup window is not lost. However in Firefox the popup window is closed when focus is lost on the browser window. The logic needs to be moved completely to the background service.

There are a few other things that needs to be wrapped up before this can be considered complete.

It depends on https://github.com/bitwarden/desktop/pull/566

2020-11-18 22:16 UTC, cscharf reviewed
@Hinton , see feedback, also need to update jslib and merge from master (again)
@kspearrin , will leave for another once-over.

2020-11-18 22:16 UTC, cscharf commented on src/background/nativeMessaging.background.ts
> +                if (error === 'Specified native messaging host not found.' || error === 'Access to the specified native messaging host is forbidden.' || error === 'An unexpected error occurred') {
This seems pretty fragile with the client needing to know what explicit error message could come from the server or other areas/services; could some regex or error "code" being embedded in those messages be better?

2020-11-19 17:42 UTC, Hinton commented on src/background/nativeMessaging.background.ts
> +                if (error === 'Specified native messaging host not found.' || error === 'Access to the specified native messaging host is forbidden.' || error === 'An unexpected error occurred') {
These errors are from the browsers so they should hopefully stay stable. I guess we could do some regex check but that may trigger for the wrong thing. On the other hand if we get an error here, it's most likely due to something going wrong with starting the proxy application.

2020-11-19 17:48 UTC, cscharf commented on src/background/nativeMessaging.background.ts
> +                if (error === 'Specified native messaging host not found.' || error === 'Access to the specified native messaging host is forbidden.' || error === 'An unexpected error occurred') {
Maybe just format/wrap this line so its not so long

2020-11-20 19:52 UTC, kspearrin requested changes

2020-11-20 19:52 UTC, kspearrin commented on src/services/browserPlatformUtils.service.ts
> +import { NativeMessagingBackground } from '../background/nativeMessaging.background';
not used? remove?

2020-11-23 13:13 UTC, Hinton commented on src/browser/browserApi.ts
> +        }
Not supported, since it doesn't support native messaging but their own communication with the bundled application. We can probably add support by re-implement the node-ipc logic into the safari companion app.

2020-12-04 14:57 UTC, cscharf approved these changes

2020-12-04 15:36 UTC, kspearrin approved these changes

2020-12-04 17:21 UTC, merged