tracked last-launched ciphers for autofill
bitwarden/browser pull request #1428
Opened 2020-10-12 17:36 UTC by addisonbeck

This is a recreation of the changes on https://github.com/bitwarden/browser/pull/1405 since that PR became stale and then I broke it horribly

It will resolve #1391

### Issue
When using the search bar to launch a url & autofill the autofill process is not using the login that was clicked, it is using the last used login previous to the clicked login.

### Resolution
We can locally track last launched logins and get that data back for autofill

2020-10-13 16:29 UTC, kspearrin commented on src/services/autofill.service.ts
> +            }
Looks unnecessary. You already call this above. I guess you could also remove line 234.

2020-10-13 16:29 UTC, kspearrin requested changes
previous comment

2020-10-13 19:34 UTC, addisonbeck commented on src/services/autofill.service.ts
> +            }
I went with removed 234, that way getLastUsedForUrl isn't called unless the data is used.

2020-10-13 19:35 UTC, kspearrin approved these changes

2020-10-13 19:41 UTC, merged

2024-10-12 15:10 UTC, mackaaij commented
Still/again an issue in Google Chrome's Bitwarden 2024.10.0. If you search your vault for a website that has multiple login items in Bitwarden and specifically choose one to launch, Bitwarden has a preference for the one to prefill (maybe alphabetically). Expected behavior is to fill the item for which the launch icon was selected.

Seems to be a regression every now and then, see #869, #1391, #1428, #1576, #1958