Add 'lock_vault' command
bitwarden/browser pull request #1450
Opened 2020-11-05 11:09 UTC by comparesheriff

Pull Request for [Contribution - Add 'lock_vault' command](https://community.bitwarden.com/t/add-lock-vault-command-to-browser-extension/15325) (addresses Feature Requests: [1](https://community.bitwarden.com/t/add-shortcut-to-manually-lock-vault/15319) and [2](https://community.bitwarden.com/t/add-global-hotkey-to-lock-log-out-without-closing-the-browser))

This Pull Request will add an command called 'lock_vault' in the manifest file without suggestedkeys (as there seems to be a limit of 4 suggestedkeys). see: [Chrome Commands](https://developer.chrome.com/apps/commands#usage)

But it will be possible to manually add a shortcut to trigger the command and lock the browser extension manually in Chrome Configure Commands (chrome://extensions/configureCommands) or Firefox About Addons (about:addons -> tools for all addons -> manage extension shortcuts)
![FirefoxAboutAddons](https://user-images.githubusercontent.com/73910438/98233530-7a59ed00-1f5f-11eb-832c-04c074b070e0.png)

Tested in Firefox and Chrome Extension

Needed:
- [ ] Feedback Safari
- [ ] Feedback Edge
- [ ] Other Feedback

2020-11-05 11:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/browser?pullRequest=1450) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/browser?pullRequest=1450) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/browser?pullRequest=1450) it.</sub>

2020-11-05 16:06 UTC, cscharf requested changes
I'm not sure how to get this to work as expected in Safari as macOS makes shortcut mapping one of the more challenging things to accomplish and I'm not sure it would be available since you can't (from what I'm seeing) add items to Safari's menu itself, only the context menu which can't be referenced from what I've seen in Preferences->Keyboard->Shortcuts->App Shortcuts->[Path].

2020-11-05 16:16 UTC, kspearrin commented on src/content/shortcuts.ts
> +    Mousetrap.bind('mod+shift+s', () => {
Safari doesn't support the user setting custom mappings for shortcuts so you'd have to explicitly pick one for them if you want the command to be available.

2020-11-05 18:06 UTC, comparesheriff commented on src/_locales/de/messages.json
> +  "commandLockVaultDesc": {
Oh sorry, I didn't know that. But now my friend has removed it in the last commit

2020-11-05 19:55 UTC, cscharf commented on src/content/shortcuts.ts
> +    // Not sure if needed, but seems to handle everything not handled in commands.background.ts:29-30
Looks like this will work for those Safari users or as a default keybinding here, so this is good, please update the comments or remove them and we should be good to go.

2020-11-05 21:57 UTC, comparesheriff commented on src/content/shortcuts.ts
> +    // Not sure if needed, but seems to handle everything not handled in commands.background.ts:29-30
I updated it to 'Default Keybinding for Safari'
Is that alright with you, or should I delete the comment altogether?

2020-11-06 15:31 UTC, cscharf commented on src/content/shortcuts.ts
> +    // Not sure if needed, but seems to handle everything not handled in commands.background.ts:29-30
Sorry yes, let's remove the comment altogether because it will apply to app platforms as there's not a Safari conditional around it, which is okay, but the comment could be misleading.

2020-11-06 15:42 UTC, kspearrin approved these changes

2020-11-06 15:43 UTC, merged

2020-11-06 15:46 UTC, cscharf commented on src/content/shortcuts.ts
> +    Mousetrap.bind('mod+shift+s', () => {
Cmd + Shift + S does nothing in Safari, I already checked, but it looks like we probably need to wrap this key combo in a condition for Safari itself, OR, change the default key combo (and add that to our help documentation).
@kspearrin / @comparesheriff