Fix safari sso
bitwarden/browser pull request #1508
Opened 2020-12-23 22:37 UTC by MGibson1

# Overview

Related to #1473. Safari SSO sign on from browser is still broken. Full SSO process is triggered, but final tab open to the SSO extension component does not work. We need to get Safari responding correctly to messages in all contexts.

# Files Changed

* **safariApp.ts**: webkit message handlers is not available from a tab opened to an extension resource. In this context, we should use safari.extension.dispatchMessage as done elsewhere.
* **content/sso.ts**: Safari app extension does not respond to chrome.runtime. Use dispatchMessage here too.
* **SafariExtensionsViewController.swift**: `createNewTab` messages for extension resources are delivered as path?query URIs only, which Safari does not interpret correctly. Detect these types of paths and navigate to the appropriate resource

# Draft Reason

The PR is currently correctly going through SSO flow up until the extension's SSO component is opened via [InitiateBrowserSso](https://github.com/bitwarden/web/blob/master/src/connectors/sso.ts#L38) from bitwarden/web. `index.html/#/sso` is indeed opened, but it does not load properly.

The only errors shown are `js.map` errors for RxJS
<img width="1341" alt="image" src="https://user-images.githubusercontent.com/18214891/103041056-e78b0700-453a-11eb-90aa-cbf240b1488d.png">

If anyone has any ideas on getting Safari to load I'd love to hear 'em!

2020-12-28 14:44 UTC, kspearrin approved these changes

2020-12-28 19:28 UTC, cscharf requested changes
Please refer to prior discussion on message command + handling in the swift to navigate the pop-up vs. opening another tab.

2020-12-28 22:24 UTC, MGibson1 commented
Thanks @cscharf for the tip on abandoning tab loading and pushing the sso to the popover, which is even better!

The changes necessary are all in **SafariExtensionsViewController.swift**.

2020-12-29 00:14 UTC, cscharf reviewed
Appears the popup is now opening, which is awesome! However, the extension is still not getting logged in (see other review comments as well on `nil` handling and casting/unwrapping)

![image](https://user-images.githubusercontent.com/3904944/103250216-d67a3580-4940-11eb-974c-76cc868548ef.png)

2020-12-29 00:14 UTC, cscharf commented on src/safari/safari/SafariExtensionViewController.swift
> +        let bundleUrl = Bundle.main.resourceURL!.absoluteURL
Only hesitation around this is the use of the `!` operator to explicitly cast the `resourceURL` without a `nil` check and/or using safe unwrapping, `if let resourceUrl = Bundle.main.resourceURL {` ... but not sure if that's necessary.

2020-12-29 00:14 UTC, cscharf commented on src/safari/safari/SafariExtensionViewController.swift
> +        webView.loadFileURL(urlComponents!.url!, allowingReadAccessTo: bundleUrl)
Same here... `urlComponents` when I tested appears to be `nil` but not sure when it wouldn't be, etc.

![image](https://user-images.githubusercontent.com/3904944/103250180-a3d03d00-4940-11eb-88e9-d410139b340a.png)

2020-12-29 01:23 UTC, MGibson1 commented on src/safari/safari/SafariExtensionViewController.swift
> +        let bundleUrl = Bundle.main.resourceURL!.absoluteURL
This particular line is a copy from line 25 of original file.

I'm fine dealing with the `nil`, but what do you think the behavior should be if it is? Just return? This is what I'm doing in the latest iteration.

2020-12-29 01:25 UTC, MGibson1 commented on src/safari/safari/SafariExtensionViewController.swift
> +        webView.loadFileURL(urlComponents!.url!, allowingReadAccessTo: bundleUrl)
Sorry about this, it's due to my messed up workflow for working in xcode and missed committing the latest changes.

It should be better handled and working now.

2020-12-29 13:40 UTC, cscharf approved these changes
it WORKS!!!! 😁  🎉

2020-12-29 13:40 UTC, cscharf commented on src/safari/safari/SafariExtensionViewController.swift
> +        let bundleUrl = Bundle.main.resourceURL!.absoluteURL
No, should be fine if it was working okay before.

2020-12-29 15:18 UTC, merged