feat: Add option to auto-copy TOTP code when page auto fills credentials
bitwarden/browser pull request #1626
Opened 2021-02-20 19:56 UTC by tomershvueli

Enable an option to auto-copy the TOTP code when auto-fill credentials is enabled. 

Discussed previously in [this Github issue](https://github.com/bitwarden/browser/issues/1184) and [this forum thread](https://community.bitwarden.com/t/totp-copy-on-autofill/17124). 

Happy to adjust any text as necessary! 

<img width="466" alt="image" src="https://user-images.githubusercontent.com/1024355/108606971-91481200-738b-11eb-8bef-9c018421dfab.png">

2021-02-20 19:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/browser?pullRequest=1626) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/browser?pullRequest=1626) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/browser?pullRequest=1626) it.</sub>

2021-02-20 20:05 UTC, tomershvueli commented on src/popup/settings/options.component.ts
> +            window.setTimeout(() => window.location.reload(), 200);
I'm curious if there's a better way to do this: I want to re-render the 'Enable TOTP Copy' checkbox if the 'Enable Auto Fill on Page Load' has been unchecked. At the moment, this re-renders the whole extension which is a bit unnecessary, but wasn't able to find similar functionality elsewhere in the extension. At the moment, this works.

2021-02-26 03:49 UTC, qianlifeng commented
Any updates on this pull request?

2021-02-26 13:50 UTC, tomershvueli commented
@qianlifeng I'm also waiting to hear for updates :) I'm not too sure who's in charge here, but would love to see this progress through and happy to answer any questions in the meantime.

2021-02-26 16:07 UTC, paulverbeke commented
would also love to have this ! thanks for your work

2021-02-26 18:49 UTC, cscharf commented
Thanks @tomershvueli! We're in the middle of preparing a big release, however we'll take a look here soon and provide feedback, etc.

@eliykat , when you can this coming week if you could review and provide feedback, would be much appreciated.

2021-03-03 05:21 UTC, eliykat reviewed
I've left some feedback for you @tomershvueli - let me know if you have any questions or want to discuss.

2021-03-03 05:21 UTC, eliykat commented on src/services/autofill.service.ts
> +            skipTotp: !fromCommand && !shouldCopyTotpOnAutoFill,
Are you sure this won't interfere with copying TOTP after other auto-fill operations? (e.g. copy TOTP after auto-filling from popup)

e.g. `fromCommand` is expressly passed in to `doAutoFillActiveTab` so that it knows how the auto-fill operation has been triggered (from hotkeys). But in your case, you're not checking that the auto-fill operation has been triggered by page load, you're just applying the settings to all auto-fill operations done by this method.

Can you do some testing around this and let me know the outcome?

2021-03-04 15:00 UTC, tomershvueli commented on src/popup/settings/options.component.ts
> +            window.setTimeout(() => window.location.reload(), 200);
Good call, see updated code.

2021-03-04 15:01 UTC, tomershvueli commented on src/popup/settings/options.component.ts
> +        this.callAnalytics('Auto Copy TOTP on Page Load', this.enableAutoTotpCopyOnAutoFill);
Honestly, glad to hear that! Removed.

2021-03-04 15:01 UTC, tomershvueli commented on src/services/autofill.service.ts
> +        const shouldCopyTotpOnAutoFill = await this.totpService.isAutoCopyOnAutoFillEnabled();
I'm with you! Corrected.

2021-03-04 15:02 UTC, tomershvueli commented on src/popup/settings/options.component.html
> +    <div class="box">
There wasn't an existing example of this so I took some liberty, happy to get notes on it. See updated screenshot in the PR description. What I did was padded-left by 15px any nested `.box` and add 5px padding-bottom to slightly separate it out a bit.

2021-03-04 15:02 UTC, tomershvueli commented on src/popup/settings/options.component.html
> +            <b>{{'warning' | i18n}}</b>: {{'experimentalFeature' | i18n}}
I agree, it looks much cleaner now and is more descriptive as a child of the 'Enable Auto Fill' anyway.

2021-03-04 15:03 UTC, tomershvueli commented on src/popup/settings/options.component.html
> +                <input id="autofill" type="checkbox" (change)="updateAutoTotpCopyOnAutoFill()"
D'oh! 😅

2021-03-04 15:07 UTC, tomershvueli commented on src/services/autofill.service.ts
> +            skipTotp: !fromCommand && !shouldCopyTotpOnAutoFill,
I did play around with most scenarios (I think) and all were working as expected. 

1. Both options (Auto fill & Auto copy) selected => overwrote my clipboard on page load, on credentials click, and on keyboard shortcut
2. Neither option selected => Only overrode my clipboard with keyboard shortcut and manual credential click
3. Auto fill unselected & auto copy selected but disabled => only overrode clipboard with shortcut and manual credential click

2021-03-11 05:59 UTC, eliykat requested changes

2021-03-11 05:59 UTC, eliykat commented on src/_locales/en/messages.json
> +    "message": "Enable Copy to Clipboard of TOTP"
Please change to "Copy TOTP to clipboard after auto-fill"

2021-03-11 05:59 UTC, eliykat commented on src/popup/scss/box.scss
> +    }
This seems like a reasonable solution, especially as there's no other example to follow here. I would just add a left border on the nested option, otherwise the box is "open". e.g.
```css
        .box-content {
            border-left: 1px solid #000000;
        }
```

I'll probably ask someone else to double-check this later to make sure we're happy with this from a UI perspective.

2021-03-11 05:59 UTC, eliykat commented on src/services/autofill.service.ts
> +        const shouldCopyTotp = copyTotpOnAutoFill && enableAutoFill;
OK, so I reviewed your comments on this section and I realised that this method is only called by:
* keyboard shortcut (`fromCommand`), or
* autofill on page load (implicitly, `!fromCommand`). Note that we'll never get here by autofill on page load if it's not already enabled.

Therefore I think we can simplify this logic and make it a bit easier to read as follows:

```typescript
const copyTotpOnAutoFill = await this.totpService.isAutoCopyOnAutoFillEnabled();
const shouldCopyTotp = fromCommand || copyTotpOnAutoFill;
```

and then

```typescript
skipTotp: !shouldCopyTotp,
```

I think this is contrary to what I said earlier, sorry, just had to think it through. The double negatives were doing my head in.

2021-03-11 16:01 UTC, tomershvueli commented on src/_locales/en/messages.json
> +    "message": "Enable Copy to Clipboard of TOTP"
👍

2021-03-11 16:02 UTC, tomershvueli commented on src/popup/scss/box.scss
> +    }
Good call. I also switched `padding` to `margin` and updated the `width` to match the other `box`es.

2021-03-11 16:03 UTC, tomershvueli commented on src/services/autofill.service.ts
> +        const shouldCopyTotp = copyTotpOnAutoFill && enableAutoFill;
Got it, this is cleaner. Double negatives always make me scratch my head too!

2021-03-11 16:04 UTC, tomershvueli commented
@eliykat I believe I addressed your comments with the latest push.

2021-03-11 22:33 UTC, eliykat commented
@cscharf I think this is ready to merge, subject to any feedback anyone might have on the UI design of the new option (i.e. the way it's nested):

<img width="394" alt="Screen Shot 2021-03-11 at 11 00 24 AM" src="https://user-images.githubusercontent.com/1024355/110816201-20449d80-8259-11eb-87f9-0ce76de51eee.png">

2021-03-12 14:54 UTC, tomershvueli commented
@eliykat just a reminder that [the JSLib PR](https://github.com/bitwarden/jslib/pull/278) should be merged in first as this depends on a constant and update to the TOTP service there :)

2021-03-13 16:14 UTC, vrnvorona commented
Hope it gets merged before next release, this bug is quite annoying.

2021-04-15 16:26 UTC, tgreer-bw commented
@cscharf just bubbling this up once more :-)

2021-04-16 03:03 UTC, eliykat commented
@cscharf @tgreer-bw I am happy with this PR and the related jslib PR. I'll add an approving review as a record of this, but it's your call whether we merge it now, merge it after the next release, or have someone else double-check first.

Looking back on it, the only part I was a little unsure of was the styling of the sub-option "Copy TOTP to clipboard after auto-fill". Currently we don't have any sub-options like this, so there's nothing to follow, but I think we'll probably need them increasingly to keep the Options page under control. I came up with some alternate styling [here](https://user-images.githubusercontent.com/31796059/114965390-d5e7b980-9eb3-11eb-83df-e43e55257b3b.png) which might be preferable, but I'm open to suggestions. If we do want to change the styling, I can do that in a small separate PR, just so that we get @tomershvueli's hard work merged in.

2021-04-16 03:05 UTC, eliykat submitted a review, later dismissed

2021-04-29 22:34 UTC, eliykat commented
Hi @tomershvueli, we've had some internal discussions around how we can handle the UI on the new option ("Copy TOTP to clipboard after auto-fill"). I think the sub-option is good in theory, but it's not a UI pattern we use elsewhere and we couldn't agree on a nice way to lay it out.

Instead, we're going to have it as a normal option (like you did to begin with). I will then make some changes separately to re-order the Options screen and add sub-headings to organize it. That will tidy things up without having to introduce a new UI pattern.

Could you please:
* Change the "Copy TOTP to clipboard after auto-fill" option back to look like all the other options, rather than a sub-option. Make sure to delete any new CSS you introduced as part of this change.
* Use the following UI strings:
  * for the control: `Automatic TOTP Copy after Page Load`
  * for the footer description: `If Auto-fill On Page Load is enabled, and your login has an authenticator key attached to it, the TOTP verification code is automatically copied to your clipboard after loading the web page.`

2021-05-05 02:29 UTC, eliykat approved these changes

2021-05-05 02:29 UTC, merged

2021-05-05 02:31 UTC, eliykat commented
Thanks @tomershvueli! I'll tidy up the options screen and do any finishing touches shortly. Unfortunately we've missed the impending release (next week) but you should see these changes in the release after that.

2021-05-05 16:50 UTC, tomershvueli commented
@eliykat thanks so much for following up and merging this in! Looking forward to using this in prod :)