remove extra context layer for Auto-fill
bitwarden/browser pull request #1756
Opened 2021-04-01 14:16 UTC by balazsorban44

This is something I am struggling with every time, and find unnecessary. I created a solution and tested it locally, works fine. I understand if this cannot be accepted in this form, so if any changes are necessary or somehow should be made optional, I am here to help!

An image of how it looks like (Note the "Auto-fill" option is gone):
![image](https://user-images.githubusercontent.com/18369201/113307093-10265800-9305-11eb-9c9d-82f24d66ebab.png)

If the user is logged out or the vault is locked, then that message will be shown instead of the options.

Existing feature request at the Bitwarden Community Forum:
https://community.bitwarden.com/t/browser-context-menu-nesting-structure-is-unnecessary-and-annoying/12532

I would even argue, that the login options could be put right into the context menu in its own section, for extreme ease of accessibility. Any reasons this wouldn't be recommended? If it's not feasible in the official extension, do you discourage me from doing it unofficially? I know about the Bitwarden icon in the top right, but accessing the context menu with right-click is usually faster. If the login options would be in the main context menu, the login process would be two simple clicks and much less effort.

2021-04-01 14:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/browser?pullRequest=1756) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/browser?pullRequest=1756) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/browser?pullRequest=1756) it.</sub>

2021-04-01 14:25 UTC, balazsorban44 commented
Objectively [Auto-fill On Page Load](https://bitwarden.com/help/article/auto-fill-browser/#on-page-load) is a good alternative that takes some of this pain away and maybe simplifies the login process even more. Still interested in your opinion about my change, or if it is plausible in some form?

2021-04-05 00:14 UTC, eliykat commented
As a UI suggestion, I think there should be a divider between "Generate Password" and the start of the list of logins. (like the dividers in the top level)

Not my call whether this is suitable for merging, but I think it's a nice minor enhancement.

Be careful using your own fork, you might experience some unexpected behaviour if there's a server/client upgrade that you get out of step with.

2021-04-05 01:15 UTC, balazsorban44 commented
Thanks for your suggestion! Adding a separator sounds like a good idea! Depending on the willingness of the acceptance of this PR, I might just add a GitHub action that will regularly pull the latest updates to my fork to keep it up to date. Ideally this could be merged if course, and I wouldn't have to maintain my fork. Will keep this open until someone could verify what should happen here. 😊

2021-05-19 17:13 UTC, jakeob28 commented
Would it be less confusing to just reverse the order of the context menu? Something like this:

- Bitwarden
  - Website Name (Account 1 Name)
    - Auto-Fill
    - Copy Username
    - Copy Password
  - Website Name (Account 2 Name)
    - Auto-Fill
    - Copy Username
    - Copy Password

In this proposal, clicking the account name would auto fill, having the same effect as hovering over the account name and then clicking auto-fill.

I believe this is more intuitive than the original suggestion (In my opinion only putting account names doesn't make it obvious that you can use them to auto-fill, and it gets even more confusing when you also see that you can hover over the other two account functions and have the same list of accounts). 

**Pros:**
- Allows one less layer to be expanded as users have the option of clicking the account name to auto fill
- Remains intuitive to users, as hovering over an account shows all potential actions instead of not having auto fill described anywhere as in @balazsorban44's original proposal

**Cons:**
- Users might not discover that they can just click the account name to auto-fill, and just always expand to the auto-fill option. This longer method would still be the same speed as the current system, however.
- I'm not sure about browser support for clickable items that also include sub-items. I believe it's possible, but for this suggestion to be an improvement the account name must be both clickable to auto-fill, and hoverable to expand sub-items.

2021-05-28 00:51 UTC, balazsorban44 commented
That's awesome! 😊 I'll do the requested changes tomorrow!

2021-06-02 22:27 UTC, eliykat commented
@cscharf I believe we're still waiting on @balazsorban44 to make the requested changes (@balazsorban44 please correct me if I'm wrong)

2021-06-02 22:41 UTC, balazsorban44 commented
So sorry, it should have been a quick fix, but I was caught up by some work and other projects :face_with_head_bandage:. I'll try to make it this week. If I am not back with some news until Sunday, feel free to implement it yourself, or close this. Don't want the PR to hang forever.

2021-06-02 22:55 UTC, eliykat commented
No worries @balazsorban44! You're doing this in your free time, it's waited a while already, it can wait a bit longer if you have more urgent things going on.

2021-06-06 22:05 UTC, balazsorban44 commented
So I needed to dig a bit more into the code (I wasn't familiar with writing Chrome Extensions from before), but I think I got it working:

![](https://i.imgur.com/S81TPmj.png)

Let me know if I should change something!

2021-06-07 03:19 UTC, eliykat requested changes
I've had a brief look over the code and highlighted a few issues. More generally:
* I think we still need the separator between "Copy password" and "Generate password"
* The "Copy username" and "Copy password" sub-menus have disappeared. These should still work the same as before (i.e. sub-menu with the option to copy username/password for each matching login item)

2021-06-07 03:19 UTC, eliykat commented on src/background/main.background.ts
> +                title: `Fill ${this.sanitizeContextMenuTitle(title)}`,
This needs to use the i18n service to make sure it's translated for non-English users. e.g. `this.i18nService.t('autoFill')`. (That'll be "Auto-fill" rather than just "fill" but I think that's fine, it'll use the existing translations.)

2021-06-07 03:19 UTC, eliykat commented on src/background/main.background.ts
> -                if (contextMenuEnabled && ciphers.length === 0) {
Is there a reason that you've removed `contextMenuEnabled` checks throughout the code? Users should still be able to disable the context menu (in popup > Settings) regardless of these changes to the layout.

2021-06-07 12:31 UTC, balazsorban44 commented on src/background/main.background.ts
> -                if (contextMenuEnabled && ciphers.length === 0) {
As far as I can tell:
https://github.com/bitwarden/browser/blob/c0f7251d77858256187a28bc14c1e4d883e0f4a3/src/background/main.background.ts#L327-L330

The`buildContextMenu` method can only run if `!menuDisabled`, and `contextMenuEnabled` is therefore not needed anymore, since `loadMenuAndUpdateBadge` also moved to `buildContextMenu`().

2021-06-07 12:34 UTC, balazsorban44 commented on src/background/main.background.ts
> +                title: `Fill ${this.sanitizeContextMenuTitle(title)}`,
Makes sense, fixed!

2021-06-07 12:48 UTC, balazsorban44 commented
> The "Copy username" and "Copy password" sub-menus have disappeared.

Looking into this.

2021-06-07 22:02 UTC, eliykat commented on src/background/main.background.ts
> -                if (contextMenuEnabled && ciphers.length === 0) {
Ok no worries - I'll have another look at it once you've fixed up the submenus.

2021-08-01 18:23 UTC, balazsorban44 commented
Just wanted to let you know I don't have the time to finish this up, unfortunately. If the maintainers would like to re-use my code in their PR or just push directly to this, I am very happy with it, would like to see this land if the team agrees with the intent!

2021-08-02 01:23 UTC, eliykat commented
Thanks for letting me know @balazsorban44. It's not a priority at the moment but I'll add a `help-wanted` label in case anyone else would like to have a crack.

2022-03-01 01:59 UTC, eliykat commented
I'm closing this due to inactivity. However, this is just housekeeping, if you decide to pick it up again then I can always reopen (or you can submit a new PR). Thanks!

2022-03-01 01:59 UTC, closed without merging