feat: add hidden char count toggle
bitwarden/browser pull request #1780
Opened 2021-04-10 16:13 UTC by mkanavakatini

[Raised a discussion here](https://community.bitwarden.com/t/toggle-hidden-character-count/28695)

[jslib work is here](https://github.com/bitwarden/jslib/pull/341)

2021-04-28 20:02 UTC, cscharf reviewed
Hi @mkanavakatini , thanks again for the contribution! Please see feedback and let me know if you have any questions.

2021-04-28 20:02 UTC, cscharf commented on src/popup/scss/misc.scss
> +    font-size: smaller;
I believe the font size needs to be at ~ 60% to 50% smaller, from the screen shot it's a bit disruptive/jarring where it's only slightly smaller than the normal password character font size.

2021-04-28 20:02 UTC, cscharf commented on src/popup/scss/misc.scss
> +.password-count {
Instead of relative/absolute positioning, would it be possible to use flex-box here? I would also think the underlying sub-text could be centered with columnar character spacing (even columns across each row), almost like a monospaced font so it's less jarring/disruptive to the eye.

2021-04-28 20:22 UTC, hampton8 commented
Hey @mkanavakatini, thanks for doing this! I live in the UK too and banks over here just love to ask for particular characters from passwords instead of the entire thing, so this would be a very welcome addition to Bitwarden. Just wanted to provide my own feedback regarding for which fields this feature would be available. I added this to the thread over on the BW Community but I’ll add it here as well for visibility’s sake.

Over on the BW forum you said:

> I will note that I’ve only added this to the custom input section, not the default password input so that it doesn’t clutter the main view.

I do think that providing this functionality for the main/default password field (just as 1Password does) as well would be beneficial for a lot of users. I believe it would in fact end up being _more_ cluttered if the user wanted to take advantage of the character count feature for their password but had to create an additional and unnecessary custom field just to do so. Users should be given the choice of using it on the default password field if they wish.

2021-04-28 20:26 UTC, cscharf commented
> I do think that providing this functionality for the main/default password field (just as 1Password does) as well would be beneficial for a lot of users. I believe it would in fact end up being _more_ cluttered if the user wanted to take advantage of the character count feature for their password but had to create an additional and unnecessary custom field just to do so. Users should be given the choice of using it on the default password field if they wish.

I would actually agree with that. Inviting some of my team to comment as well.

2021-04-29 09:20 UTC, Hinton commented
On the [forums](https://community.bitwarden.com/t/add-a-reference-number-under-password-characters-for-websites-that-require-3rd-7th-12th-character/14124/18) a user showed a screenshot from 1Password, which also increases the font size in this mode, to make it easier to read. I quite like it since it would make the feature more generally applicable outside of number matching.
Which would also give additional value to having it added to the main password field.

Although we would need to re-consider how we display buttons on the password field in this case. Adding additional icons clutters things, a potential work around would be to move the "check password" and "count toggle" to a "more" dropdown. (https://fontawesome.com/v4.7.0/icon/ellipsis-v) seems a good icon candidate)

2021-04-29 09:34 UTC, hampton8 commented
That seems like a good idea @Hinton - I've always been a fan of 1Password's large type feature.

And yes I think moving the check password and large type/number characters toggles to a drop down would be sensible. They're both very useful tools but are/would be used infrequently enough to warrant them being an extra click away.

Although I do think that the original design @mkanavakatini came up with might actually be a great way of implementing the character count feature in the mobile app, where there isn't the screen real estate to display a large type pop up.

2021-07-01 19:34 UTC, sym0nd0 commented
Another vote for Large Type, like 1Password does it, please. I'm just in the midst if migrating from 1P to Bitwarden and this is probably the only thing that's missing.

2021-07-02 10:53 UTC, mkanavakatini commented
Thanks all for the feedback, not sure why I missed the initial comments but I've read through now and will implement your suggestions and provide updates in the coming week!

2021-07-25 00:49 UTC, mkanavakatini commented
Good for another look @cscharf. I've added functionality to the standard password input as well as the hidden text custom field input now. There are other suggestions here such as large type & a 'more' button but I have only focused this PR on the original feature at this stage - let me know if you specifically want those features in this PR though.

![image](https://user-images.githubusercontent.com/13248401/126884290-d70229ca-5b4b-4096-8083-365f7c0d7a79.png)

2021-07-30 20:01 UTC, cscharf reviewed
Just one comment on the SCSS file, however also adding @eliykat to please look at the markup and logic updates.

2021-07-30 20:01 UTC, cscharf commented on src/popup/scss/misc.scss
> +    &.bg-grey {
Can we please just use `&:nth-child(odd)` or similar in order to apply the appropriate background color in this instance vs. explicitly overriding `bg-grey` so theming is more obvious here? Similar comment left on the pipe in the jslib PR as well.

2021-07-30 21:36 UTC, mkanavakatini commented
@cscharf feedback address and just added one extra thing - added a `.slim` action-button class when the field length is >19 and the count is on:

![image](https://user-images.githubusercontent.com/13248401/127713770-ac5c8de9-54b0-4c9c-8322-21183bcea875.png)

2021-08-04 08:12 UTC, eliykat requested changes
Hi @mkanavakatini, overall I think this looks great! However, the icons are quite cluttered, which I know we discussed above but didn't come to any conclusion on. Our designer has provided [this wireframe](https://www.figma.com/proto/6fvTDa3zfvgWdizLQ7nSTP/Numbered-Letters?page-id=0%3A1&node-id=5%3A34&viewport=1711%2C899%2C0.6730318069458008&scaling=scale-down&starting-point-node-id=5%3A12) to show how we'd like it to work. The details are:

* Use an "expand" icon to collapse all but the Copy option
* If user clicks "expand" show all other options
* Expanded options remain visible until user closes the Login item

If you can implement this, I'll then check the logic and we should be good to go 🚀

2021-08-06 19:09 UTC, mkanavakatini commented
I've made the requested changes @eliykat thanks for the input & and pass on a thanks to the designer for the wireframe! Let me know if any more feedback 👌🏽 

![image](https://user-images.githubusercontent.com/13248401/128559997-d0da243c-7da3-4cf2-b0a8-d796021ab8f8.png)

2021-08-13 09:50 UTC, eliykat requested changes
This looks great! The only changes I think are required are to update the templating logic to better match the wireframe.
* in this PR, the "show count" button only appears if the "show password" button is clicked first. In the wireframe, the "show count" button appears next to the other action buttons as soon as you click the chevron. You don't have to "show password" first. (This helps discoverability.)
  * I expect "show count" and "show password" to be alternatives. e.g. if I toggle "show password" on, and then click "show count", it should toggle "show password" off. And vice versa. Or you can toggle them on/off independently.
  * you'll need to make sure that "show count" goes through the same password reprompt check as "show password"
* I understand your thinking for using a hamburger menu icon as the "off" state of the "show count" button, but it doesn't clearly communicate what the button does. (Especially because in all other situations that's a menu icon.) I think we just have to keep the same icon (`fa-list-ol`) in both states.
* the chevron should not appear on text or boolean custom fields, because they don't have any (extra) action buttons to display

We generally try to have feature parity across all clients. Once we get browser hammered out, would you be able to replicate it across web and desktop? I think desktop should follow roughly the same UI, web might be a bit different - I'll check. But they both share jslib and use Angular as well. I'll also check what we're doing with mobile.

Thanks again for your work on this one! If I've missed or misunderstood anything, just let me know.

2021-08-31 08:48 UTC, mkanavakatini commented
Hey @eliykat sorry for the delay, have had some time away from my desk!

Thanks for your feedback - understood everything and will implement when I have a free moment. I'm more than happy to get stuck into the other repos to release this feature across the board. I'm an FE React developer in my day-to-day though so I may need a little more direction when it comes to the other platforms!

2021-08-31 23:47 UTC, eliykat commented
All good! Feel free to tag me here if you have any questions, or DM me on [Gitter](https://gitter.im/bitwarden/Lobby).

2021-09-26 15:02 UTC, mkanavakatini commented
Updated view
![image](https://user-images.githubusercontent.com/13248401/134813226-09868005-fbfe-4670-8c92-65eb5bba7390.png)

2021-11-26 06:02 UTC, eliykat commented
Hi @mkanavakatini, sorry for the delay at my end. I'll review this next week for you so that we can finish it off. There are now some merge conflicts (again, my fault), if you can resolve those as well, I would appreciate that.

2021-12-03 03:38 UTC, eliykat requested changes
Some minor comments below. 
* note that all our web vault buttons have changed from using `<a href="#">` to using `<button type="button">` elements (which is really the correct element to use).  This will probably throw a lot of merge conflicts, but should be easy to resolve. Please also update the elements you're adding to be buttons (and make sure to specify `type="button"` on all of them, very important).
* the action buttons move up & down slightly as you toggle the character count. Can you fix that somehow?

Otherwise looks great, sorry again for the delay, I'll keep an eye out for any further changes so we can get it merged.

2021-12-03 03:38 UTC, eliykat commented on src/popup/vault/view-custom-fields.component.html
> +                    <i class="fa fa-lg fa-bars" aria-hidden="true"></i>
Should be the icon with the numbers on it:
```suggestion
                    <i class="fa fa-lg fa-list-ol" aria-hidden="true"></i>
```

2021-12-03 03:38 UTC, eliykat commented on src/popup/vault/view.component.html
> +                            <i class="fa fa-lg fa-bars" aria-hidden="true"></i>
```suggestion
                            <i class="fa fa-lg fa-list-ol" aria-hidden="true"></i>
```

2022-01-28 04:28 UTC, eliykat commented
Looks good, thanks for sticking with it! I've merged with master, run code formatting tools, and fixed a minor visual bug, using the same fix you used for the action buttons. I'll merge this next week after we've cut release candidate branches for February, so this should go out in the March release.

2022-01-28 06:20 UTC, hampton8 commented
Excellent news! I've been waiting for this feature to come to Bitwarden for years! Thank you for your kind work @mkanavakatini 🙂

2022-02-23 06:30 UTC, eliykat commented
I'm requesting a final review from the team now that I've also added code directly to this. See my comment on the jslib PR: https://github.com/bitwarden/jslib/pull/341#issuecomment-1048477215

2022-02-23 14:06 UTC, MGibson1 requested changes
The changes to `box.scss` are having unintended consequences in other areas. I tried to check everywhere we're using box, but I doubt I was completely thorough. These are comparisons of current `master` branch (left) to this PR (right). At the least we need to vert-align the left- and right-hand items.

<img width="867" alt="image" src="https://user-images.githubusercontent.com/18214891/155333901-d3f3105b-ed18-4b85-b1a2-636aca92f741.png">

The hidden text rows are a little larger than the others now:

<img width="867" alt="image" src="https://user-images.githubusercontent.com/18214891/155334191-7fa70a58-67b2-4251-a450-417a4d442aae.png">

The copy and totp icons are misaligned as well:

<img width="867" alt="image" src="https://user-images.githubusercontent.com/18214891/155334700-e2ecc6fa-804b-4b61-ab73-97f37ad99a70.png">

What are the general box changes doing?

2022-02-23 22:07 UTC, eliykat commented
Ah good point. It was to stop the box row contents from jumping around when you toggle the character count, given that it changes the height of the row. But I'll investigate further.

2022-02-23 23:36 UTC, eliykat commented
It looks like that was just cause by an errant margin on the action-buttons. See updated screenshots below (left is this branch, right is prod)

![Screen Shot 2022-02-24 at 9 27 14 am](https://user-images.githubusercontent.com/31796059/155427343-04a7d3bf-c482-46b6-93a4-5780385381f1.png)
![Screen Shot 2022-02-24 at 9 28 02 am](https://user-images.githubusercontent.com/31796059/155427349-80eccdca-21cb-4e84-b59b-be025fc1882c.png)
![Screen Shot 2022-02-24 at 9 29 01 am](https://user-images.githubusercontent.com/31796059/155427353-730be220-cf2a-401d-a959-890f54dfc4be.png)

I don't like messing with the box model either, but the alternative is that the action buttons jump around:

https://user-images.githubusercontent.com/31796059/155427449-e5a150ff-a5ae-4f82-8aa9-3d0de5b9b514.mov

This seems to be the smallest/simplest way of resolving the issue without taking these divs out of the general box design (or without making bigger changes such as having fixed-size rows). I'll give QA a heads up, otherwise I think it's okay.

2022-02-24 03:11 UTC, MGibson1 approved these changes
Much more comfortable with these `box.scss` changes

2022-02-24 03:11 UTC, merged

2023-12-26 17:15 UTC, 1Mark commented
@mkanavakatini great job! Is there anyway we could get it to copy to the clipboard when you click on a character?