Feature/password reprompt
bitwarden/browser pull request #1784
Opened 2021-04-14 10:11 UTC by Hinton

## Objective
Adds support for requiring master password re-prompt before accessing hidden fields on ciphers. Also marks card numbers as a secret to ensure it's protected.

### Code Changes
- **src/background/main.background.ts**: Prevent context menu from containing ciphers which requires reprompt.
- **src/popup/components/action-buttons.component.ts**: Protect action button copy.
- **src/popup/services/services.module.ts**: Remove unnecessary exports
- **src/popup/vault/add-edit.component.html**: Add prompt setting.
- **src/popup/vault/current-tab.component.ts**: Prevent autofill of protected ciphers
- **src/popup/vault/view.component.html**: Make card numbers hidden.
- **src/popup/vault/view.component.ts**: Protect edit, clone, share and autofill.
- **src/services/autofill.service.ts**: Prevent autofillon protected ciphers.

### Testing Considerations
We should verify all expected values are protected and cannot be accessed without prompting for master password.

### Screenshots
![image](https://user-images.githubusercontent.com/137855/114693270-b87ee800-9d19-11eb-8ece-f55467c2fa40.png)
![A2ojNTCG8Y](https://user-images.githubusercontent.com/137855/114693302-bf0d5f80-9d19-11eb-9664-eba6136dbd97.gif)

2021-04-21 15:02 UTC, MGibson1 requested changes
I don't see why, but I'm getting different behavior on my local server vs our self-hosted test server. Locally, all ciphers seem to default to reprompt, which isn't desirable. Additionally, I can't save ciphers. On the self-hosted server, they are not defaulting to reprompt, but saving a cipher as requiring a reprompt does not persist and no re prompt is triggered.

I don't see any requirements for server-side synchronization, but I haven't been able to figure out what I'm doing wrong locally to test this out

2021-04-22 09:33 UTC, Hinton commented
@MGibson1 Are you running the password-reprompt branch on server? Since I've added an additional field to the ciphers the server would probably error out due to unexpected content.

2021-04-22 09:34 UTC, Hinton commented on src/popup/vault/view.component.ts
>          }
I changed the `share` signature to return a bool so that child components could determine if they should proceed. We don't have any code depending on the value outside of this.

2021-05-03 16:53 UTC, MGibson1 commented
That was the problem. I missed the server requirements and sql migration.

2021-05-03 17:02 UTC, MGibson1 approved these changes
This all looks good. My only concern is adding an indication on why auto-fill shortcuts aren't working.

We discussed ways to indicate including a banner notifying that popup interaction is required and a tab that unlocks the item.

I'm OK leaving these as improvements, but please create tickets for them :)

2021-05-03 18:56 UTC, merged