Use cdk-virtual-scroll for long cipher lists
bitwarden/browser pull request #1858
Opened 2021-05-21 04:51 UTC by eliykat

## Objective

Boost performance on large vaults (see e.g. #1597) by reducing the number of elements rendered at once. (This replaces a previous PR which used a different library which wasn't working out for me.)

Currently we have paging logic, which loads the first 100 ciphers, then the next 100, etc, as you scroll down. However:
* this prevents the user from accessing all their ciphers at once
* performance will degrade as more items load in
* this is not implemented in all areas of the app (in particular, search results)
* the `ngx-infinite-scroll` library used for this purpose does not work with Ivy, which has prevented us switching over to it (see #1412).

Here's an example of how you can break it currently (I'm doing this very intentionally, but it can happen). Note that the extension fails to re-open afterwards, I had to restart Chrome.

https://user-images.githubusercontent.com/31796059/119082776-181b9200-ba42-11eb-854f-d41dce2198c6.mov

Instead we can use [cdk-virtual-scroll](https://material.angular.io/cdk/scrolling/overview) from the Angular CDK.

> The <cdk-virtual-scroll-viewport> displays large lists of elements performantly by only rendering the items that fit on-screen. Loading hundreds of elements can be slow in any browser; virtual scrolling enables a performant way to simulate all items being rendered by making the height of the container element the same as the height of total number of elements to be rendered, and then only rendering the items in view. Virtual scrolling is different from strategies like infinite scroll where it renders a set amount of elements and then when you hit the end renders the rest.

Here's how it performs after these changes:

https://user-images.githubusercontent.com/31796059/119082780-1b168280-ba42-11eb-8933-c37c07e3196e.mov

- [x] better performance
- [x] easier to implement across different parts of the app
- [x] no external dependencies
- [x] compatible with Angular Ivy (I tested `dist` builds in all browsers to make sure)

2021-05-29 02:35 UTC, madhanhere requested changes

2021-05-29 02:35 UTC, madhanhere commented on src/popup/app.module.ts
> +import { ScrollingModule } from '@angular/cdk/scrolling';
align the imports

2021-05-29 02:35 UTC, madhanhere commented on src/popup/vault/current-tab.component.html
> +                <app-cipher-row *ngFor="let c of loginCiphers" [cipher]="c" title="{{'autoFill' | i18n}}" [showView]="true"
Just a suggestion instead using the variable name `c` we can use `loginChiper` and I can see few other places below variable name `c` is used there we can use appropriate name.

2021-05-29 02:35 UTC, madhanhere commented on src/popup/vault/groupings.component.html
> +            <div class="box list" *ngIf="nestedFolders && nestedFolders.length">
we can use the safe navigation operator (?) to make it simple `*ngIf="nestedFolders?.length"`

2021-06-02 18:06 UTC, cscharf commented on src/popup/vault/groupings.component.html
> +            <div class="box list" *ngIf="nestedFolders && nestedFolders.length">
Actually, this should not be using falsey logic but explicit logic.

```suggestion
            <div class="box list" *ngIf="nestedFolders != null && nestedFolders.length > 0">
```

2021-06-02 18:21 UTC, cscharf commented on src/popup/vault/current-tab.component.html
> +                <app-cipher-row *ngFor="let c of loginCiphers" [cipher]="c" title="{{'autoFill' | i18n}}" [showView]="true"
What he said.

2021-06-02 22:52 UTC, eliykat commented on src/popup/vault/groupings.component.html
> +            <div class="box list" *ngIf="nestedFolders && nestedFolders.length">
Good point

2021-06-02 22:53 UTC, eliykat commented
I've fixed the few style issues that were pointed out. I've also removed the use of `virtualScroll` for the favorites list, as this should not reasonably have enough items to cause any slowdown, so `virtualScroll` would probably just add overhead there.

2021-06-10 19:55 UTC, cscharf reviewed
I think this looks good Thomas, however I'm adding Oscar on here as well for a quick review/sanity check if there's anything I missed.

2021-06-11 08:00 UTC, Hinton approved these changes
Looks good to me, but I'm not quite familiar with the previous unlimited scroll.

2021-06-14 21:35 UTC, merged