fix: radio instead of dropdown
bitwarden/browser pull request #1894
Opened 2021-06-13 15:37 UTC by knhash

**Feature name:**

    Replace the drop down for password/passphrase option with a radio button choice

**Feature Description**

There are only two options in the drop down, would it be better to replace it with a radio button for choice?
- Aids in discoverability: I completely missed the option for a whole year before I thought to click on the option and see what it contains.
- Less number of interactions: It would take 1 less click to get the same result

Community Forum post: https://community.bitwarden.com/t/radio-choice-password-passphrase/30636

2021-06-30 02:09 UTC, eliykat requested changes

2021-06-30 02:09 UTC, eliykat commented on src/popup/generator/password-generator.component.html
> +            <a class="box-content-row text-primary" href="#" appStopClick appBlurClick (click)="copy()">{{'copyPassword'
Something weird has happened here, maybe caused by your Visual Studio Code formatting rules? Please undo this change.

2021-06-30 02:09 UTC, eliykat commented on src/popup/generator/password-generator.component.html
> +</content>
Please undo this change

2021-06-30 02:09 UTC, eliykat commented on src/popup/generator/password-generator.component.html
> +            <div class="box-content-row">
Please copy across any applicable feedback from here: https://github.com/bitwarden/desktop/pull/955

2021-06-30 02:09 UTC, eliykat commented on src/popup/generator/password-generator.component.ts
> +        this.passTypeOptions = [
You can revert the changes in this file once these changes have been lifted up to `jslib`.

2021-07-01 20:36 UTC, knhash commented on src/popup/generator/password-generator.component.html
> +            <div class="box-content-row">
Done. Removed unnecessary for label.

2021-07-01 20:36 UTC, knhash commented on src/popup/generator/password-generator.component.html
> +            <a class="box-content-row text-primary" href="#" appStopClick appBlurClick (click)="copy()">{{'copyPassword'
Undone.

2021-07-01 20:39 UTC, knhash commented on src/popup/generator/password-generator.component.ts
> +        this.passTypeOptions = [
Done.

2021-07-02 01:47 UTC, eliykat requested changes
Same changes as desktop

2021-07-02 01:47 UTC, eliykat commented on src/popup/generator/password-generator.component.html
> +                        {{o.name | i18n}}
Remove `i18n` pipe per my comment on `desktop`

2021-07-02 01:47 UTC, eliykat commented on src/popup/generator/password-generator.component.html
> -                <label for="type" class="sr-only">{{'type' | i18n}}</label>
Put this `<label>` back in with some changes - see my comment on `desktop`

2021-07-02 06:46 UTC, knhash commented on src/popup/generator/password-generator.component.html
> +                        {{o.name | i18n}}
Done.

2021-07-02 06:46 UTC, knhash commented on src/popup/generator/password-generator.component.html
> -                <label for="type" class="sr-only">{{'type' | i18n}}</label>
Done.

2021-07-07 11:38 UTC, eliykat approved these changes

2021-07-07 11:39 UTC, merged