Redefine cipher "share" to "move to organization"
bitwarden/browser pull request #1903
Opened 2021-06-17 16:03 UTC by MGibson1

# Overview

# Overview

The term "Share" is confusing to users because it implies maintaining ownership and control of a cipher while allowing others to access it as well. It also implies the ability to revoke access or to stop sharing -- neither of these things is true.

In addition to the share term being misleading, the [`fa-share-alt`](https://fontawesome.com/v4.7/icon/share-alt) icon implies a forking of the cipher item rather than transferring ownership.

When a cipher is "shared" it is irrevocably taken over by an organization. This occurs for good cryptographic and security reasons. The better solution to this is to revise the communication around "sharing." To that end, this work changes the term "share" to "move to organization" and the icon is changed to [`fa-cube`](https://fontawesome.com/v4.7/icon/cube), which is used to indicate a collection. The act of moving an item to an organization is denoted by [`fa-arrow-circle-o-right`](https://fontawesome.com/v4.7/icon/arrow-circle-o-right) rather than `fa-share-alt`.

# Screen shots
#### Organization owned item in list
<img width="432" alt="image" src="https://user-images.githubusercontent.com/18214891/122432633-1a96dc00-cf5b-11eb-9799-0d01b655852e.png">
#### Move to organization action
<img width="432" alt="image" src="https://user-images.githubusercontent.com/18214891/122432842-49ad4d80-cf5b-11eb-80c0-e5184f984fb0.png">
#### Move to organization component
<img width="432" alt="image" src="https://user-images.githubusercontent.com/18214891/122432992-69dd0c80-cf5b-11eb-82ff-dac1f80997b1.png">
#### Move to organization success toast
<img width="432" alt="image" src="https://user-images.githubusercontent.com/18214891/122433046-76f9fb80-cf5b-11eb-8c92-71d6279ac421.png">

# Draft Reason
Waiting on bitwarden/jslib#412

2021-06-21 03:38 UTC, eliykat requested changes

2021-06-21 03:38 UTC, eliykat commented on src/_locales/en/messages.json
> +    "message": "Bitwarden allows you to share your vault items with others by using an organization account. Would you like to visit the bitwarden.com website to learn more?"
I know you're using existing wording, but while we're here - is "organization account" the correct wording? I haven't seen it anywhere else, and to me, it implies that organizations have a separate login. Can we just say "by using organizations"?

2021-06-21 03:38 UTC, eliykat commented on src/popup/settings/settings.component.html
> +            <a class="box-content-row box-content-row-flex text-default" href="#" appStopClick appBlurClick (click)="share()">
Needs a line break after `appBlurClick` to maintain consistency with other lines & comply with 120 char ruler.

2021-06-21 17:31 UTC, MGibson1 commented on src/_locales/en/messages.json
> +    "message": "Bitwarden allows you to share your vault items with others by using an organization account. Would you like to visit the bitwarden.com website to learn more?"
Yeah I agree, good catch

2021-06-21 23:53 UTC, eliykat approved these changes

2021-06-22 20:43 UTC, eliykat approved these changes

2021-06-22 20:44 UTC, merged