Use password field with toggle to set PIN
bitwarden/browser pull request #1911
Opened 2021-06-22 04:46 UTC by eliykat

## Objective
Fix #887: 
>The PIN input screen is insecure in the sense that you can read what you input into it. The screen to input your PIN to unlock it is secure though. I figure that this is an oversight.

## Code changes
* `settings.component.ts` - expand the template literal we use for the swal2 dialog, add event handler for show/hide logic
* `plugins.scss` - minor styling to make the elements sit inline. Bootstrap styles (e.g. `form-inline`) didn't seem to work here.

I don't like constructing the swal2 template within the component like this, but despite much messing around with swal2 was unable to find a better way.

2021-06-22 08:39 UTC, Hinton requested changes
I worked on some similar PRs https://github.com/bitwarden/desktop/pull/959, to add show/hide button to the password reprompt dialogs.

In this case I suspect we could refactor the PR to use a modal instead? Which would let us use the Angular templates instead? If we keep it as a SweetAlert dialog, we will need to sanitize any unsafe html.

2021-06-22 08:39 UTC, Hinton commented on src/popup/settings/settings.component.ts
> +                        placeholder="${this.i18nService.t('pin')}">
We'll want to run Angular sanitizer on the `i18nService.t` response.

2021-06-22 20:10 UTC, eliykat commented
That makes sense - that must be why we were setting the attributes via javascript rather than inline. 

I like the idea of your modal service much more - it saves having to recreate all this stuff from scratch when we can just slap an Angular component together. I'll check out that PR and revert this to draft in the meantime.

2021-09-07 07:19 UTC, eliykat commented
Closing this, I'll submit a new PR using dynamic modals instead.

2021-09-07 07:19 UTC, closed without merging