Format 16-digit credit card numbers in groups of 4
bitwarden/browser pull request #1940
Opened 2021-07-07 20:05 UTC by nathanhleung

This PR formats 16-digit credit card numbers in 4 groups of 4 digits each for better readability.

# Community Forum Posts

Feature request post: https://community.bitwarden.com/t/display-card-numbers-in-groups-to-make-them-easier-to-read/12042

GitHub contribution post: https://community.bitwarden.com/t/display-card-numbers-in-groups-to-make-them-easier-to-read/31541

# Before

<img width="384" alt="Screen Shot 2021-07-07 at 12 58 56 PM" src="https://user-images.githubusercontent.com/10874225/124821057-3e3aba00-df3c-11eb-9ab4-8d50bfc9455f.png">

# After

<img width="384" alt="Screen Shot 2021-07-07 at 12 57 45 PM" src="https://user-images.githubusercontent.com/10874225/124820911-121f3900-df3c-11eb-9236-ce87fdc6d886.png">

# Potential Todos

For this PR, or another future PR:

- Should the `CreditCardNumberPipe` file be put in `jslib`? It looks like other pipes are in `jslib` rather than in the `browser` repo
- Support other credit card formats listed in https://baymard.com/checkout-usability/credit-card-patterns

2021-07-07 20:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/browser?pullRequest=1940) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/browser?pullRequest=1940) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/browser?pullRequest=1940) it.</sub>

2021-07-07 22:49 UTC, eliykat reviewed
This would be a nice UX improvement for sure.

The pipe would go in `jslib`, because it'll be used by desktop, browser and web so that we have a consistent UX across all relevant clients. If you're unfamiliar with submodules, please check out the `CONTRIBUTING.md` doc in jslib for a primer.

It looks like this will only format the number after it reaches 16 digits, can you format it as the user types instead?

Will the space be copied when the user copies the credit card number from Bitwarden? That could interfere with copy/pasting into forms that do not expect spacing. e.g. if they're expecting 16 characters, the last 4 digits will be cut off because the spaces will be counted towards the limit - or the form could just reject spaces. I think the spacing needs to be purely visual rather than affecting the actual stored value.

Keen to hear any solutions you might have.

2021-07-08 17:05 UTC, nathanhleung commented
Thanks for the review!

> The pipe would go in `jslib`, because it'll be used by desktop, browser and web so that we have a consistent UX across all relevant clients. If you're unfamiliar with submodules, please check out the `CONTRIBUTING.md` doc in jslib for a primer.

Sounds good, as a first step I'll move the pipe to `jslib` and open a separate PR there.

> It looks like this will only format the number after it reaches 16 digits, can you format it as the user types instead?

Yes, this PR only formats 16-digit credit card numbers specifically in the `view` component. It does not do any formatting of the credit card number in the text input in the `add-edit` component.

Formatting the number as the user types is a bit more tricky than just formatting the displayed value (I'll need to implement [input masking](https://css-tricks.com/input-masking/) — which probably involves some more JS that might be significantly heavier than the current 27 line delta of this PR) so I'm thinking formatting the credit card number as the user types could be done in a separate PR. What do you think?

> Will the space be copied when the user copies the credit card number from Bitwarden? That could interfere with copy/pasting into forms that do not expect spacing. e.g. if they're expecting 16 characters, the last 4 digits will be cut off because the spaces will be counted towards the limit - or the form could just reject spaces as invalid input. I think the spacing needs to be purely visual rather than affecting the actual stored value.

Great catch, I didn't think of this — based on my local testing (I clicked the "Copy" icon and ran the extension autofill against https://www.roboform.com/filling-test-all-fields), it looks like this spacing is purely visual. It does not affect the actual stored value.

Does all of this sound good in terms of where I should go from here?

2021-07-08 23:00 UTC, eliykat commented
I missed that this change was only applied in `view` and not `add-edit`. That's actually ideal, because then the change is only visual and shouldn't affect the stored value. Copying won't be a problem either. So yes, please go ahead and move the pipe into jslib. I don't think it should need any other changes, other than to:
* update imports etc. arising from the refactor
* add a trailing newline at EOF of the `credit-card-number.pipe.ts`.

2021-07-08 23:05 UTC, eliykat requested changes
I missed that this change was only applied in `view` and not `add-edit`. That's actually ideal, because then the change is only visual and shouldn't affect the stored value in the model. Copying won't be a problem either. So yes, please go ahead and move the pipe into jslib. I don't think it should need any other changes, other than:
* the couple of minor changes noted below
* update the `view` templates in desktop and web to use this pipe. Could you open some PRs for these?

I agree there's no need to make any changes to the `add-edit` page. Thanks!

2021-07-08 23:05 UTC, eliykat commented on src/popup/vault/credit-card-number.pipe.ts
> +}
Please add a trailing newline here (our code style)

2021-07-08 23:05 UTC, eliykat commented on src/popup/app.module.ts
> +import { CreditCardNumberPipe } from './vault/credit-card-number.pipe';
This will need to be updated once the pipe is moved into jslib.

2021-07-08 23:20 UTC, nathanhleung commented on src/popup/app.module.ts
> +import { CreditCardNumberPipe } from './vault/credit-card-number.pipe';
Opened a PR in jslib: https://github.com/bitwarden/jslib/pull/427

2021-07-08 23:20 UTC, nathanhleung commented on src/popup/vault/credit-card-number.pipe.ts
> +}
Added the newline in my jslib PR: https://github.com/bitwarden/jslib/pull/427

2021-07-15 09:48 UTC, eliykat reviewed
I'm not sure if this is ready for review yet - I noticed your jslib PR, but you haven't updated this PR.

Please remove the pipe from this PR and use the pipe in jslib instead.

If you just haven't gotten to this yet then that's fine, just wanted to make sure you weren't waiting on me.

2021-08-05 01:12 UTC, eliykat commented
Please refer to the discussion on the related [jslib PR](https://github.com/bitwarden/jslib/pull/427) for the current status of this feature.

2022-05-02 15:19 UTC, Hinton commented
Hi @nathanhleung,

Thank you for the contribution, this was implemented in https://github.com/bitwarden/browser/pull/2527.

2022-05-02 15:19 UTC, closed without merging