[Feedback] Add Linked Field as a custom field type
bitwarden/browser pull request #1963
Opened 2021-07-19 06:32 UTC by eliykat

## Objective

This PR is a partial solution to #1621 - "Auto-fill isn't working for a specific site". It contains two main changes.

**New custom field type: Linked**

A "Linked" custom field is linked to a standard field on that item. Instead of entering a value for the custom field, the user selects which standard field it should refer to. When the custom field is auto-filled, it will auto-fill that value.

Edit screen:
![Screen Shot 2021-07-19 at 4 16 18 pm](https://user-images.githubusercontent.com/31796059/126112354-51f9716d-2753-4efb-b413-5252cfe6f035.png)

View screen (link icon denotes linked field):
![Screen Shot 2021-07-19 at 4 16 10 pm](https://user-images.githubusercontent.com/31796059/126112389-52b35784-4c1b-4ed8-a33c-93cec075c6d0.png)

Rationale: 
* we often tell users to use custom fields to solve autofill problems, because it allows them to specify the HTML `id` or `name` of the input elements. However, this can result in maintaining multiple sets of data. e.g. generating a new password, then copying that password to a Hidden custom field. This removes that duplication of data and effort.
* our autofill script will never match every site on the internet. This gives users the power to configure autofill on their favourite sites, rather than relying on us to make high-level changes to autofill that may or may not fix their specific site.

Possible issues:
* if the user has multiple logins for 1 site, they'll have to configure custom fields for each login. The alternative would be to 'lift up' the autofill configuration to an account level rather than the login-level, but that would be a more major change. I thought we could start with this solution and see whether this is actually a problem first.

**New context menu option: Copy custom field name**

It's bad UX to require users to open up dev tools and read the HTML, just to create custom fields. This adds a new right-click option that will copy either the HTML `name` or `id` to the clipboard. It will prefer whichever is unique.

![Screen Shot 2021-07-19 at 4 17 05 pm](https://user-images.githubusercontent.com/31796059/126113242-afe133ff-b3d5-44f4-bc6a-5a1346a79fbc.png)

This does not rely on adding Linked Fields and could be merged separately - but this was good motivation to add it.

## Code changes

2021-07-20 18:19 UTC, cscharf reviewed
I _believe_ this looks good, provided some feedback and comments in slack but also just one minor change here. I would like some others on the team to look at this as well.

2021-09-08 16:41 UTC, MGibson1 requested changes
Nice job, this is pretty surgical work for some really nice added functionality.

I did have a few questions and improvements.

2021-09-08 16:41 UTC, MGibson1 commented on src/popup/vault/add-edit.component.html
>                              <input id="fieldName{{i}}" type="text" name="Field.Name{{i}}" [(ngModel)]="f.name"
How about extracting this to a component while you're at it? We have too many examples of these kinds of if chain in a larger views. Extracting them would really simplify our html in general

2021-09-08 16:41 UTC, MGibson1 commented on src/popup/vault/add-edit.component.html
> +                                [disabled]="!cipher.viewPassword && !f.newField">
I'm confused about why this disables the picker. Are these meant to be immutable? Why does `viewPassword` matter?

2021-09-08 16:41 UTC, MGibson1 commented on src/popup/vault/view.component.html
> +                        <i class="fa fa-link"></i>{{cipher.getLinkedFieldi18nKey(field.value) | i18n}}
Add span to field value. 

Also, right now the link icon and the field name are butted right up against eachother. Try and emulate the styling found in the `Clone Item`, `Move to  Organization`, `Delete Item` buttons seen at the bottom of the form.

this might be a relatively big refactor given that the structure of the boxes is different and I'm not 100% sure where that styling is coming from

2021-09-08 16:41 UTC, MGibson1 commented on src/services/autofill.service.ts
> +                        if (val == null && matchingField.type === FieldType.Boolean) {
I think this needs to be outside the else.

If the linked field is a boolean and is null, we still want to handle that as a false.

2021-09-13 06:39 UTC, eliykat commented on src/popup/vault/add-edit.component.html
> +                                [disabled]="!cipher.viewPassword && !f.newField">
Looks like I copied the template for Hidden custom fields and didn't update the logic, good find.

2021-09-13 07:34 UTC, eliykat commented on src/popup/vault/view.component.html
> +                        <i class="fa fa-link"></i>{{cipher.getLinkedFieldi18nKey(field.value) | i18n}}
I think this is looking good now, without too many changes:

![Screen Shot 2021-09-13 at 5 32 06 pm](https://user-images.githubusercontent.com/31796059/133042533-276a914c-9500-4c6a-87b2-d54419fd2a82.png)

2021-09-13 07:47 UTC, eliykat commented on src/services/autofill.service.ts
> +                        if (val == null && matchingField.type === FieldType.Boolean) {
That's a good point. However, I don't think we have any boolean fields that form part of the cipher itself. e.g. we have boolean fields like "Favorite", but nothing that would hold auto-fillable data.

We'd also want to make sure that the underlying/linked field is a boolean type before making the assumption that `null == false`, and I don't think we could test for that at runtime. I'm inclined to leave this alone for now given that it's a future possibility only.

2021-09-16 05:08 UTC, eliykat commented on src/popup/vault/add-edit.component.html
>                              <input id="fieldName{{i}}" type="text" name="Field.Name{{i}}" [(ngModel)]="f.name"
@MGibson1 This was a good suggestion, I split it into its own set of PRs here: https://github.com/bitwarden/jslib/pull/489. I'll wait until that refactor is merged before continuing here.

2021-09-16 05:08 UTC, eliykat commented
Reverting to draft until https://github.com/bitwarden/jslib/pull/489 is merged.

2021-09-27 04:19 UTC, eliykat commented
This is out of draft and ready for review again.
* the custom fields refactor has been merged and this PR has been updated accordingly
* other review feedback has been addressed above
* some minor fixes and tweaks per the git log above

2021-09-27 14:16 UTC, MGibson1 commented on src/popup/vault/view-custom-fields.component.html
> +                    *ngIf="field.value && field.type !== fieldType.Boolean && field.type !== fieldType.Linked &&
Don't we want a copy button for linked fields? I know you could just copy from the field it's linking, but I don't see a good reason to not have this button.

2021-09-27 14:16 UTC, MGibson1 commented on src/services/autofill.service.ts
> +                        if (val == null && matchingField.type === FieldType.Boolean) {
I hear you that it's not in current type definitions, but this would be a timebomb bug. It's unlikely we'd remember this as a need for implementation if we're adding a bool to a template.

You should be able to check the underlying type with the `typeof` operator combined with `constructor.name` to catch `Boolean` objects:
```typescript
typeof(<<field>>) === 'boolean' || (typeof(<<field>>) === 'object' && <<field>>.constructor.name === 'Boolean')
```

Not the prettiest code in the world, but we can hide it in a Util method and use typescript to our advantage: https://www.typescriptlang.org/docs/handbook/2/narrowing.html#using-type-predicates.

Does the above address your concerns with implementing this default?

2021-09-29 05:17 UTC, eliykat commented on src/services/autofill.service.ts
> +                        if (val == null && matchingField.type === FieldType.Boolean) {
I'm happy to dig into this further. I tried what you suggested, but got the error: `TypeError: Cannot read properties of null (reading 'constructor')`.

I think that's because, if we use this as an example:

`favorite: Boolean = null;`

Then `typeof cipher.favorite === object`, however because `null` is a primitive type and not actually a real object, `cipher.favorite.constructor.name` throws an error: `TypeError: Cannot read properties of null (reading 'constructor')`.

Because the value is `null`, we have no way of knowing at runtime whether it is intended to be a bool or not. The only thing that indicates that is the typescript annotation, which is compile time only.

I think we'd have to record this information especially for linked fields. Currently the `linkedFieldOptions` are just key-value pairs, but we could change this to be a class, with each class containing the property name, i18n key, plus a new `isBoolean` property to record whether the underlying field is boolean. That would go unused for now but would allow for use in the future.

2021-09-29 05:26 UTC, eliykat commented on src/popup/vault/view-custom-fields.component.html
> +                    *ngIf="field.value && field.type !== fieldType.Boolean && field.type !== fieldType.Linked &&
For the same reason, I thought that there was no good reason _to_ have the button. I assume that if someone wants to copy the linked value they'll just copy it directly from the actual field. I thought the copy button in this context would just be confusing (copy what?) and add clutter.

2021-11-03 11:15 UTC, MGibson1 approved these changes

2021-11-03 21:37 UTC, MGibson1 approved these changes

2021-11-03 21:40 UTC, merged