Small accessibility fixes for notifications
bitwarden/browser pull request #1980
Opened 2021-07-30 20:42 UTC by patrickhlauke

* suppress the `<table>` semantics with `role="none"` (though in the medium term, better to drop the table and use CSS grid or similar)
* don't hide the logo link (it's still keyboard focusable, so makes no sense to have `aria-hidden="true"` on it)
* add appropriate `alt` to the logo image
* use `<button>` for the close button, not a link
* add `<title>` to the overall page

2021-07-30 20:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/bitwarden/browser?pullRequest=1980) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/bitwarden/browser?pullRequest=1980) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/bitwarden/browser?pullRequest=1980) it.</sub>

2021-07-31 17:51 UTC, patrickhlauke commented
might have a try at actually implementing a grid layout and removing tables altogether

2021-09-01 12:33 UTC, djsmith85 requested changes
Hi @patrickhlauke thank you for the contrib. Looks good so far. Just some minor things.

1) If you could get rid of the whitespace changes, it would make the diff a bit cleaner.
2) The never and add buttons should also be aligned to the right, same as before
3) Great idea to have a better alt-text on the Bitwarden logo, but possibly add a more descriptive one for the close-button too (i18n.close instead "X")

2021-09-02 07:48 UTC, eliykat commented
Just FYI, we'll likely finalise and merge this PR in the next day or so, which is making changes to the notificationBar layout: https://github.com/bitwarden/browser/pull/1409/
It might be a good idea to hold off on making further changes on this one until that other PR is merged, as it'll create conflicts for you.

2021-09-02 10:09 UTC, patrickhlauke commented
apologies folks, after a burst of activity on filing issues/PRs, I got sucked into a bit of a timesink and haven't been able to follow through on things. hoping to carve out some time later this month. per @eliykat's comment above, i'll hold off making any changes on this PR until the other changes have been merged (and rebase/rework it if necessary)

2021-09-18 18:36 UTC, patrickhlauke commented
going to wait and see if https://github.com/bitwarden/browser/pull/1988 gets merged, and then having a fresh stab in a new PR

2021-09-18 21:43 UTC, patrickhlauke commented
superseded by https://github.com/bitwarden/browser/pull/2076/

2021-09-18 21:43 UTC, closed without merging