A11y: Change links to buttons
bitwarden/browser pull request #1988
Opened 2021-07-31 19:11 UTC by patrickhlauke

- more semantically accurate, will expose these as buttons to assistive technologies (in general, whenever you have a `href="#"` that's a strong indication that it's actually a `<button>` you want to use)
- note: while having block-level elements like `<div>` inside a `<button>` is an html validation error, it does not affect functionality as long as there's no more structure inside it

2021-08-09 20:10 UTC, patrickhlauke commented
changing to draft for now, as i've noticed some instances where the default button styles now override some of the styles that were previously taken from/applied to the links the extension (wrongly) used instead. will tweak this further to hopefully catch these instances.

would be good to gauge interest in this PR though before I spend considerably more time on it. i.e. are there non-obvious reasons why links, rather than buttons, have been used for these controls?

2021-08-10 04:17 UTC, eliykat commented
Hi @patrickhlauke, I've noticed your issues and PRs relating to accessibility and I really appreciate you spending time in this area. I have your PRs on my to-do list and hopefully won't keep you waiting too long, we're just quite busy at this point in the release cycle.

If `<button>` elements can be made to look and behave the same as `<a>` elements do currently, but are more accessible and more semantically accurate, then that sounds like a win to me. That said, I'll double check with the team to make sure there's nothing I'm missing.

2021-08-10 08:13 UTC, patrickhlauke commented
hey @eliykat, good to hear. sorry, my message wasn't intended as a "i submitted this X days ago, why has it not been actioned/merged yet", but more of a general gauge of how likely the idea was to be considered. sorry, re-reading the above i see my tone was leaning far too much towards giving the impression it was the former. long story short: all good, no meaning to rush you folks. i'll fiddle some more with the styles and once i get to the point where i think i caught all stylings/made them look the same as now, i'll set the PR back to ready for review 👍

2021-09-01 12:46 UTC, addisonbeck reviewed
Hi @patrickhlauke , just wanted to let you know getting this merged is on my immediate todo list.

>  sorry, re-reading the above i see my tone was leaning far too much towards giving the impression it was the former

I didn't read anything forward in your tone at all, no worries. This PR is certainly something we are interested in. There is no non-obvious underlying reason `<a>` tags are used instead of buttons here, other than (as you discovered) that there is preexisting styling that gets in the way here.

Otherwise, I noticed a couple places that were missing `type="button"`, listed as suggestions below.

2021-09-01 12:46 UTC, addisonbeck commented on src/popup/accounts/home.component.html
> +        <button (click)="launchSsoBrowser()" class="btn block">
```suggestion
        <button type="button" (click)="launchSsoBrowser()" class="btn block">

```

2021-09-01 12:46 UTC, addisonbeck commented on src/popup/accounts/lock.component.html
> +            <button appStopClick (click)="logOut()">{{'logOut' | i18n}}</button>
```suggestion
            <button type="button" appStopClick (click)="logOut()">{{'logOut' | i18n}}</button>
```

2021-09-18 16:50 UTC, patrickhlauke commented
spent some more time on this PR, and i *think* i've now got everything now looking exactly as it previously did (i.e. changing the links to buttons left no discernible visual/layout differences) - unless I overlooked something somewhere

2021-09-28 18:56 UTC, patrickhlauke commented
If possible, suggest merging this soon, as otherwise it'll keep hitting merge conflicts (spent some time tonight just fixing things up)

2021-10-01 13:35 UTC, addisonbeck requested changes
I think we are seeing unexpected line break control changes on this one too, and one other quick formatting fix. After that we should be able to get this merged in.

2021-10-01 13:35 UTC, addisonbeck commented on src/popup/scss/buttons.scss
> +}
I'm not sure what's going on with this diff, but it is showing the entire file as changed. Possibly the same line break issue as your other [PR](https://github.com/bitwarden/browser/pull/1990#issuecomment-930971418)?

2021-10-01 13:35 UTC, addisonbeck commented on src/popup/accounts/home.component.html
> +
```suggestion
```

2021-10-01 13:40 UTC, patrickhlauke commented
sorry, mea culpa yes ... serves me right for not configuring VS Code properly on the second machine. will push up a commit to fix this

2021-10-01 13:57 UTC, patrickhlauke commented
Line ending encoding fixed

2021-10-04 17:02 UTC, addisonbeck approved these changes
Major thanks again @patrickhlauke 🙏

2021-10-04 17:02 UTC, merged

2021-10-04 19:16 UTC, patrickhlauke commented
no worries @addisonbeck ... my pleasure (these are the low-hanging fruit changes ... there's a few more fundamental things that will be more tricky to tackle, but we'll get to them bit by bit ;) )