Add issue template and template chooser
bitwarden/browser pull request #2056
Opened 2021-09-06 08:53 UTC by Hinton

## Objective
Simplify the workflow for submitting issues and finding help links by adding a new issue template which utilizes github issue forms.

2021-09-06 15:18 UTC, djsmith85 requested changes

2021-09-06 15:18 UTC, djsmith85 commented on .github/ISSUE_TEMPLATE/bug.yml
> +      options:
I know that these are the most common ones, but as users use all different kinds of browser I suggest changing it to an input field. Maybe add a couple as a placeholder, so users see what they need to enter

2021-09-07 03:53 UTC, eliykat commented on .github/ISSUE_TEMPLATE/bug.yml
> +      options:
Ideally this should just be a list of our supported browsers. I assume we don't want bug reports for unsupported browsers.

2021-09-07 10:33 UTC, djsmith85 commented on .github/ISSUE_TEMPLATE/bug.yml
> +      options:
True, let's stick with the dropdown

2021-09-07 10:33 UTC, djsmith85 approved these changes

2021-09-08 19:32 UTC, djsmith85 approved these changes

2021-09-09 09:55 UTC, merged