Automatic biometrics prompt
bitwarden/browser pull request #2065
Opened 2021-09-09 16:59 UTC by danepowell

https://community.bitwarden.com/t/automatic-biometrics-prompt-on-open-popup/17383

This primarily rebases and cleans up the work originally performed by @cho-m (thanks!)

It requires a blocking prompt if the desktop application isn't open. This isn't ideal, but making this more user-friendly (i.e. a toast instead of blocking dialog) would require significant refactoring of the crypto service and should probably be handled as a followed-up.

Requires https://github.com/bitwarden/jslib/pull/483

2021-09-10 12:14 UTC, Hinton requested changes
Thanks for taking a stab at this @danepowell. I've done a quick review and written some quick thoughts.

2021-09-10 12:14 UTC, Hinton commented on src/popup/settings/options.component.ts
> +        this.disableAutoBiometricsPrompt = await this.storageService.get<boolean>(
Until we've resolved the blocking nature of the dialog we should default this to false, since it's a change in behavior for existing users. (i.e. null => true)

2021-09-10 12:14 UTC, Hinton commented on src/popup/accounts/lock.component.ts
> +            window.setTimeout(async () => {
We already have a set timeout just above this, could we not move this logic there as well?

2021-09-10 12:14 UTC, Hinton commented on src/popup/settings/options.component.html
> +        <div class="box">
Since we have the "Unlock with biometric" setting in settings, I believe it would make more sense to have the checkbox in settings as well. Which fits more with how the settings are shown in Desktop.

2021-09-10 16:53 UTC, danepowell commented
Thanks for the feedback, I think it's resolved in the latest commits.

2021-09-14 16:59 UTC, Hinton requested changes
The `disableAutoBiometricsPrompt` needs to default to true in `lock.component` as well. Otherwise looks good.

2021-09-14 16:59 UTC, Hinton commented on src/popup/accounts/lock.component.ts
> +        const disableAutoBiometricsPrompt = await this.storageService.get<boolean>(
This should default to true as well.

2021-09-14 16:59 UTC, Hinton commented on src/popup/accounts/lock.component.ts
> +        this.isInitialLockScreen = (window as any).previousPopupUrl == null;
I'm not completely familiar with the `previousPopupUrl` system, but could this not be moved into `ngOnInit`? Would avoid fragmenting the logic.

2021-09-15 15:21 UTC, Hinton commented
@danepowell Before we can merge this we will need to get @cho-m to sign the CLA. It seems the CLA bot missed this due to the commit being co-authored.

@cho-m Would you be willing to sign the Bitwarden CLA, https://cla-assistant.io/bitwarden/browser?

2021-09-15 20:56 UTC, danepowell commented on src/popup/accounts/lock.component.ts
> +        this.isInitialLockScreen = (window as any).previousPopupUrl == null;
`previousPopupUrl` is only set in the constructor. It didn't work as expected running in `ngOnInit`.

2021-09-15 21:12 UTC, cho-m commented
Thanks for working on this. I signed CLA so should be good on that side.

2021-09-15 21:20 UTC, cho-m commented on src/popup/accounts/lock.component.ts
> +        this.isInitialLockScreen = (window as any).previousPopupUrl == null;
I remember trying this out before and it didn't work within `ngOnInit`.

Another option I was looking into, but didn't get change to fully explore, was to reuse some code from Desktop app. Over there, it adds information during routing within jslib's **auth-guard.service.ts** (https://github.com/bitwarden/jslib/blob/master/angular/src/services/auth-guard.service.ts#L30).

2021-09-16 19:03 UTC, Hinton commented
@danepowell I've merged the jslib PR. And I did some quick testing and from a functional perspective things looks good. One thing I did notice though is that checkbox is enabled even when biometric is turned off. In the desktop application we disable the checkbox since it doesn't serve a function without biometrics and I believe we should do the same here to keep things consistent.

We also need to update the `jslib` submodule pointer to the latest `master`. I think that's the last things before we can merge this.

Thanks for signing the CLA @cho-m!

2021-09-16 22:31 UTC, danepowell commented
Great catch, thanks. I updated the settings to work the same as the desktop app (disabled if biometric disabled).

2021-09-17 08:22 UTC, Hinton approved these changes
LGTM, going to merge this. Please note that it unfortunately won't be included in the next release since it missed the cut-off date. But it should be included in the release after.

Thank you for the contribution @danepowell @cho-m.

2021-09-17 08:22 UTC, merged