Patrickhlauke issue1987
bitwarden/browser pull request #2223
Opened 2021-12-13 21:42 UTC by patrickhlauke

## Type of change
- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
Add structural/semantic heading markup when text acts as a heading and is visually styled as a heading, but currently marked up as a generic `<div>`. This will result in assistive technologies/screen readers actually announcing things as headings (e.g. "heading level 1, Settings ... heading level 2, Manage ... heading level 2, Security ..." on the settings view). It also allows screen reader users to quickly navigate by headings (e.g. in NVDA, using the `H` key to jump to the next heading directly, `Shift+H` to jump to the previous heading).

Closes https://github.com/bitwarden/browser/issues/1987

## Code changes
Use `<h1>` and `<h2>` elements where appropriate. To make sure there's no visual change, tweaked the main CSS to:

* remove the forced theme `color` for headings - this is unnecessary, as headings will inherit the color of their context/parent anyway, and is overly specific, as it will otherwise override/explicitly set the color (and would otherwise necessitate extra styles to make sure heading color is defined for different contexts)
* make the heading size and weight match that of regular text (as the text acting as headings is already getting explicitly styled through classes anyway)

## Screenshots

Screenshots here to show that there is no actual visual change.

Current (taking settings as an example):

![current appearance of the Settings view](https://user-images.githubusercontent.com/895831/145892734-b9f38d6c-a2e7-44a9-957e-52a406404a3c.png)

After this PR:

![the look of Settings after this PR, indistinguishable from the current one](https://user-images.githubusercontent.com/895831/145892801-bd2ac810-94f4-4deb-87e9-3e5d49c5b722.png)

## Testing requirements

Suggest testing all screens/views using a screen reader, checking that no text acting as a heading has been missed out, and that visually hidden headings are correctly announced, 

## Before you submit
- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2021-12-15 23:09 UTC, djsmith85 reviewed
@patrickhlauke Thank you again for a great contribution. Did you change any files in jslib? Maybe it's just pointing to an old commit hash in jslib. 

Will try and review in the next couple of days

2021-12-16 00:47 UTC, patrickhlauke commented
> Did you change any files in jslib? Maybe it's just pointing to an old commit hash in jslib.

@djsmith85 my knowledge of git is fairly primitive, and yes the jslib thing keeps popping back up as being modified even though i keep doing upstream git pulls and clean npm installs etc which i would have thought fix this. but i'm probably missing something...

short answer: no i didn't change anything in jslib. if you can give me a pointer on how i could fix it here, i'd be happy to update this PR so it's clean

2021-12-16 00:56 UTC, patrickhlauke commented
ah, a bit of stackoverflowing tells me that `git submodule update --init  --recursive` is probably what i should have done. doing it now finally clears the annoying issue of jslib looking like it's modified...but doesn't seem like i can push any update for this PR somehow as there's nothing to commit.

2021-12-16 18:10 UTC, djsmith85 requested changes
@patrickhlauke I've just had a look at your changes and tested these with NVDA on Windows. These are look very good. Just a minor thing with the export component.

Regarding the jslib changes. You branch is pointing to an older version of jslib. Updating your branch with browsers-current master should set it to commit jslib @ **8fc3cf50d2967212ffbbf0d57cac71d0774aa2a8**. 

The changes will look something like this:
```
diff --git a/jslib b/jslib
index 24fe8360..8fc3cf50 160000
--- a/jslib
+++ b/jslib
@@ -1 +1 @@
-Subproject commit 24fe836032354d4ec39435776e54dd0995e1b389
+Subproject commit 8fc3cf50d2967212ffbbf0d57cac71d0774aa2a8
```
Then stage the jslib-file, commit and push it. This should resolve it.

If you have any issues or need assistance let me know.

2021-12-16 18:10 UTC, djsmith85 commented on src/popup/settings/export.component.html
> +        </h1>
NVDA doesn't pick this up. I assume it's because the Master password fields get focused immediately. Using `h` or `shift+h` announces there are no headings. Hovering over the title announces it properly.

2021-12-16 20:09 UTC, patrickhlauke commented
> Regarding the jslib changes

done it i think

2021-12-16 20:14 UTC, patrickhlauke commented on src/popup/settings/export.component.html
> +        </h1>
odd, i'll have a play later tonight and see what's going on

2021-12-16 22:59 UTC, patrickhlauke commented on src/popup/settings/export.component.html
> +        </h1>
Had a look. It works fine for me, but yes once you get to the Settings > Export vault screen, master password field receives focus (that's a separate issue i plan to have a think about ... what the best initial focus for each view should be. toying with the idea of saying the `<h1>` should be what gets initial focus across all screens, for consistency and for announcement in assistive technologies once user swiches between views).

once you're on the screen, hit `NVDA+Space` to get out of forms mode (focus still remains on the master password field, but you're not editing/typing in anymore). then `Shift+H` should go to the `Export Vault heading level 1`

2021-12-17 00:26 UTC, djsmith85 commented on src/popup/settings/export.component.html
> +        </h1>
Yeah, that works. We are good to merge then.

2021-12-17 00:27 UTC, djsmith85 approved these changes

2021-12-17 00:27 UTC, merged