Add clearer accessible names for password generator options (A-Z, a-z, 0-9, !@#$%^&*)
bitwarden/browser pull request #2233
Opened 2021-12-18 22:22 UTC by patrickhlauke

## Type of change
- [ ] Bug fix
- [x] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
Currently, the labels for the `A-Z`, `a-z`, `0-9`, `!@#$%^&*` fields in the password generator are difficult to work out/cryptic for assistive technology users: `A-Z` and `a-z` are announced by screen readers exactly the same, and the `!@#$%^&*` is announced as "at number dollar percent and star" (as screen readers will, by default, not announce some of those punctuation marks when presented like that as a nonsensical string in particular). This PR adds new `aria-label` attributes for the checkboxes to provide a more human-understandable accessible name for each of these checkboxes to make them understandable.

Closes https://github.com/bitwarden/browser/issues/1985

## Code changes

* added new entries for the various `messages.json` files. Translated the ones I could, but the remaining ones will need to be translated further.
* added `attr.aria-label` to the four checkboxes in `password-generator.component.html` with reference to the relevant new `messages.json` entries.

## Screenshots

No visible UI change.

## Testing requirements
Test with a screen reader (e.g. NVDA). Set focus to the checkboxes and note how they are announced.

## Before you submit
- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2021-12-18 22:25 UTC, patrickhlauke commented
Comparison video (using a test item) of navigating the four checkboxes. note how currently NVDA announces `A-Z` and `a-z` the same, and how `!@#$%^&*` is announced as "at number dollar percent and star" (which is cryptic, *and* misses out some of the characters as they're not announced by default as they're silent punctuation). after this PR, the checkboxes are announced with a more human-understandable accessible name: "Uppercase (A-Z)", "Lowercase (a-z)", "Numbers (0-9)", "Special characters (!@#$%^&*)"

https://user-images.githubusercontent.com/895831/146657056-96e68a8d-f821-44c2-8fe3-e26bc6a67419.mp4

2021-12-19 10:55 UTC, djsmith85 requested changes
@patrickhlauke Thank you again for your contribution. This is looking good and I tested it with NVDA on Windows. 

Thank you for also providing translations. Unfortunately a lot of it was unnecessary. We use [CrowdIn](https://crowdin.com/project/bitwarden-browser) for our translations. You only need to add entries to the `src/_locales/en/messages.json` and they get uploaded to CrowdIn once this PR is merged. Our strong community translates those strings and we merged them back in before a release.

Please remove all changes to the `messages.json` files, besides the one mentioned above.

2021-12-19 11:52 UTC, patrickhlauke commented
@djsmith85 should I keep the translations that are fully done and that I'm confident are correct (Italian, German, French, since I'm fluent in those; Spanish, Portuguese, where I have a good grasp of the language, though not 100% fluid)?

2021-12-19 12:09 UTC, djsmith85 commented
@patrickhlauke I really appreciate the effort, but we'd get merge conflicts when pulling the translations from CrowdIn and someone from the team would have to resolve these. So it would be easier for us, if you removed them from the PR. If you are up for it, I'd ask you to add them in CrowdIn once we've merged and pushed the new messages to CrowdIn. 

Saying that though, it is quite a lot of work and usually our community picks these changes up quite fast. They receive an email notification as soon as new messages are available, at least I do.

2021-12-19 12:12 UTC, patrickhlauke commented
Ok, kein Problem ... dann machen wir's halt nur auf Englisch hier in der PR :)

2021-12-19 12:15 UTC, djsmith85 commented
Vielen Dank für dein Verständnis ❤️

2021-12-19 12:22 UTC, patrickhlauke commented
Done

2021-12-19 12:31 UTC, djsmith85 approved these changes
@patrickhlauke Thank you

2021-12-19 12:31 UTC, merged