[Account Switching] Base changes for account switching
bitwarden/browser pull request #2250
Opened 2021-12-29 14:15 UTC by djsmith85

## Type of change

- [ ] Bug fix
- [X] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
This in building on the awesome work from @addisonbeck and @differsthecat with https://github.com/bitwarden/browser/pull/2110. Unfortunately some issues came up with the merge and application prettier (overwritten bug fixes and not correctly applied prettier config). So I checked out a fresh version of master and recreated the changes that were made in https://github.com/bitwarden/browser/pull/2110. While doing that I discovered a few necessary changes to the BrowserComponentState model and the browser specific state-servce.

Marking this as draft as this PR is basis for a discussion between @addisonbeck , @differsthecat and me on how to bring account switching into browser.

## Testing requirements

There are no functional changes here, but the storage mechanism for the entire app was swapped. We should perform a regression here, specifically surrounding login and settings.

## Before you submit

- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-01-25 17:55 UTC, djsmith85 commented on src/popup/accounts/login.component.ts
> +  }
Updated with your fix in jslib to always rememberEmail on clients that need it 😄

2022-01-25 17:56 UTC, djsmith85 commented on src/background/main.background.ts
> -  userVerificationService: UserVerificationServiceAbstraction;
The service has been re-added. It was needed during the export of a vault

2022-01-25 19:46 UTC, addisonbeck approved these changes
Looks good to me. Lets leave this unmerged for a bit (like maybe until tomorrow morning) to see if others provide any feedback.

2022-01-27 06:25 UTC, eliykat requested changes
Nice work all, I can see this was a big job. I've left some comments below, but due to time differences, please feel free to get someone else to review any further changes or dismiss anything that doesn't apply.

PS. I like the refactor of naming callbacks that are passed into constructors - feels easier to keep track of the constructor arguments that way.

2022-01-27 06:25 UTC, eliykat commented on src/popup/services/services.module.ts
> +      useFactory: getBgService<BaseStateServiceAbstraction>("stateService"),
Recommend you use `useExisting` here to refer to the `StateServiceAbstraction` token, rather than duplicating this line. Seems a bit cleaner.

2022-01-27 06:25 UTC, eliykat commented on src/popup/settings/settings.component.ts
> -    let timeout = await this.vaultTimeoutService.getVaultTimeout();
This is just a wrapper for `stateService`, doesn't need to be changed unless you're intending to deprecate this method on `vaultTimeoutService`. Although I admit it feels a little inconsistent with having to get the action from `stateService` directly.

2022-01-27 06:25 UTC, eliykat commented on src/popup/vault/ciphers.component.ts
> +            this.popupUtils.setContentScrollY(window, this.state?.scrollY, this.scrollingContainer),
You already do a null check above, no need for the `?` here.

2022-01-27 06:25 UTC, eliykat commented on src/popup/vault/groupings.component.ts
> +    super(collectionService, folderService, baseStateService);
Is the `baseStateService` necessary here? Shouldn't it accept the subclass as if it were the parent?

2022-01-27 06:25 UTC, eliykat commented on src/services/browserPlatformUtils.service.ts
> +    const theme = (await this.stateService.getTheme()) as ThemeType;
I think this method should always return a `ThemeType` instead of returning a string and casting it, but we can leave that for another time if you want.

2022-01-27 10:55 UTC, djsmith85 commented on src/background/nativeMessaging.background.ts
> +      this.postMessage(message as any);
I also addressed my concerns in the original PR https://github.com/bitwarden/browser/pull/2290. Oscar has created a tech debt ticket for it.

2022-01-27 11:35 UTC, djsmith85 commented on src/background/main.background.ts
> +    if (accounts.length > 0) {
I like your solution, concise and elegant with the use of `.every()`

2022-01-27 11:36 UTC, djsmith85 commented on src/background/nativeMessaging.background.ts
> +        if (!this.stateService.getBiometricLocked()) {
We should absolutely `await` it 😁

2022-01-27 11:36 UTC, djsmith85 commented on src/popup/vault/ciphers.component.ts
> +            this.popupUtils.setContentScrollY(window, this.state?.scrollY, this.scrollingContainer),
Removed the unneeded null check

2022-01-27 11:38 UTC, djsmith85 commented on src/popup/vault/groupings.component.ts
> +    super(collectionService, folderService, baseStateService);
It's been a while and no idea why we were passing in 2 instances. The browser specific one will do

2022-01-27 13:16 UTC, addisonbeck commented on src/background/main.background.ts
> +    if (accounts.length > 0) {
Ftr: doing things this way doesn't work on desktop - it was the original way I wrote everything up and it always returned true. I didn't dig very far into figuring out why.

2022-01-27 17:22 UTC, Hinton commented on src/background/main.background.ts
> +    if (accounts.length > 0) {
You would need to add a `Promise.all` in the mix as well.

2022-01-27 17:22 UTC, Hinton commented on src/background/nativeMessaging.background.ts
> +  // Should only have one of theses.
Yes. `these`.

2022-01-27 17:23 UTC, Hinton commented on src/background/nativeMessaging.background.ts
> +      this.postMessage(message as any);
Correct, we have a tech debt to tackle these. There weren't really a nice way to do it.

2022-01-27 17:26 UTC, Hinton commented on src/background/nativeMessaging.background.ts
> +        if (!this.stateService.getBiometricLocked()) {
😢 yes.

2022-01-27 19:44 UTC, djsmith85 commented on src/services/browserPlatformUtils.service.ts
> +    const theme = (await this.stateService.getTheme()) as ThemeType;
Created a ticket for it as it's not blocking the merge of this PR

2022-01-27 19:53 UTC, djsmith85 commented on src/popup/settings/settings.component.ts
> -    let timeout = await this.vaultTimeoutService.getVaultTimeout();
Actually important to call the vaultTimeoutService as it actually cleans up any erroneous vaultTimeouts.

2022-01-27 19:54 UTC, djsmith85 commented on src/background/main.background.ts
> +    if (accounts.length > 0) {
Reverted to the simple loop but removed the length check as commented

2022-01-27 19:59 UTC, addisonbeck commented on src/popup/accounts/login.component.ts
> +  protected alwaysRememberEmail: boolean = true;
This is pretty semantic, and follows a pattern already set up in other clients that set a default at the property level. If you feel strongly about this lets discuss, but for now I think we should do that separately if need be and update desktop too.

2022-01-27 20:57 UTC, eliykat commented on src/popup/accounts/login.component.ts
> +  protected alwaysRememberEmail: boolean = true;
I don't feel that strongly ;) if that's a pattern that you're following then all good

2022-01-27 21:02 UTC, eliykat commented on src/background/main.background.ts
> +    if (accounts.length > 0) {
Dang promises!

2022-01-27 21:13 UTC, eliykat approved these changes

2022-01-27 21:22 UTC, merged

2022-10-08 16:23 UTC, terion-name commented
What about browser extention?