Update badge number when saving a new entry
bitwarden/browser pull request #2284
Opened 2022-01-22 10:37 UTC by djsmith85

## Type of change

- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
When saving a new entry via the Add Login prompt (Bar) the badge number  did not get updated. Only after a page refresh the updated badge appears.

Asana task: https://app.asana.com/0/1169444489336079/1201703036655950/f
## Code changes

- **src/background/notification.background.ts:** 
  - Minor refactoring to use early return and renamed message variables
  - Send message `addedCipher` when a new entry was added so `refreshBadgeAndMenu` is called
- **src/content/message_handler.ts:** Add `addedCipher` to `forwardCommands` so that the message is passed on to main

## Testing requirements
The badge number should update when saving a new entry. This should be happening even if the vault was locked beforehand

## Before you submit

- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-01-23 22:43 UTC, eliykat requested changes
Love this UX stuff you're working on, really makes the product feel polished.

2022-01-23 22:43 UTC, eliykat commented on src/background/notification.background.ts
> -        queueMessage.type === NotificationQueueMessageType.addLogin &&
Do you still need to check the message type before continuing?
Even if we've implicitly narrowed it down to this message type, it should be an explicit check (a) so it's clear and (b) to avoid errors if we add another message type in the future.

2022-01-23 22:43 UTC, eliykat commented on src/background/notification.background.ts
>        if (queueMessage.type === NotificationQueueMessageType.changePassword) {
I noticed that the `NotificationQueueMessageType` is a string enum. Is there a reason for this, or can it be changed to a normal (number) enum?

Also, the enum property names should be PascalCase (e.g. `ChangePassword`).

2022-01-24 10:54 UTC, djsmith85 commented on src/background/notification.background.ts
> -        queueMessage.type === NotificationQueueMessageType.addLogin &&
Good idea, just in case we extend the enum at some point.

2022-01-24 10:55 UTC, djsmith85 commented on src/background/notification.background.ts
>        if (queueMessage.type === NotificationQueueMessageType.changePassword) {
Adjusted the casing and changed it to a simple enum. I think the type property was originally a string and when I created the enum for it I just kept it that way. No real need for that.

2022-01-24 21:34 UTC, eliykat approved these changes

2022-01-25 07:16 UTC, merged