[PS-102] BEEEP: Tab-change performance improvements
bitwarden/browser pull request #2447
Opened 2022-03-14 14:31 UTC by djsmith85

## Type of change

- [X] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective
As reported by some users the extension is quite active even while not visiting new sites as it reacts to all tab changes. This includes multiple state changes while a tab is loading but also the multiple state changes to tabs other than the currently focused tab (also across multiple windows).

This can be noticed by CPU spikes, higher memory usage and a higher amount of idle wake-up-calls.

This PR aims to reduce the calls to `refreshBadgeAndMenu` which seems to have the highest impact on the above mentioned values. Also not checking the `notificationQueue` for new logins tabs that currently have no interaction by the user and the collection of pageDetails for auto-fill.

CPU spikes and memory consumption are expected when the extension is performing operations in the background as for example: `sync`, `checking vault timeout`, `scanning a page for changes/login fields` but with the reduction in calls of the latter, this should improve the overall performance.

Closes #769 and #2198 

I hope this will also solve cases where the badge and menu do not correspond to the vault's lock state (unlocked/locked):
https://github.com/bitwarden/browser/issues/1717
https://github.com/bitwarden/browser/issues/2323
https://github.com/bitwarden/browser/issues/2455

Asana task: https://app.asana.com/0/1200578627114106/1201993816674939/f

## Code changes
- **src/background/main.background.ts:** 
  - Do not pass in `this` (main) to `notification.background`
  - Remove instantiation of `windows.background` - logic moved into `tabs.background`
  - Pass `true` to `refreshBadgeAndMenu` on `logout` which shortens the time to re-draw badge and menu
- **src/background/notification.background.ts:**
  - Remove constructor dependency on `main.brackground`
- **src/background/tabs.background.ts:** 
  - Listen to `chrome.windows.onFocusChanged` to set currently focusedWindowId
  - Remove messages send that nothing subscribes to
  - Only react to tab changes of currently focused window
  - Check status of tab and onlt react to change if tab is active
- **src/background/windows.background.ts:** 
  - Deleted, as logic has been moved to `tabs.background`\
- **package-lock.json:** Changes after running `npm i`

## Screenshots
I've monitored the changes using the built-in task manager in Chrome/Firefox and below are comparision videos for before and after my applied changes.

As a testbed, I always used a freshly started chrome/firefox profile, installing the dev-extension, closing the welcome page and opening 10 tabs of [https:bigstar](https://bigstar.pl/) (as this site changes it's title when not in focus) and one focused new tab (browser default page).

### Firefox
[Before video](https://user-images.githubusercontent.com/2670567/159126792-8581a50d-1edd-49b5-955b-dce2c42b4050.mp4)
[After video](https://user-images.githubusercontent.com/2670567/159126804-c70e1757-f1df-4c34-b285-53a13c956b89.mp4)

### Chrome
[Before video](https://user-images.githubusercontent.com/2670567/159126671-4f13ca24-df58-49c2-93a3-45e22c568aca.mp4)
[After video](https://user-images.githubusercontent.com/2670567/159126663-b4a7f42f-b2aa-49ac-9925-765244922a84.mp4)

### Safari
As I am currently unable to test my changes on Mac/Safari, I'd love for one of the devs to test this, before progressing to QA.

## Testing requirements
Testing should occur with all of our supported browsers, and include multiple open windows and tabs and jumping between them while checking the test cases below:
- The badge and menu should always show the correct state, between un-/authed, un-/locked
- The badge should always show the correct amount of matched entries
- Make sure auto-fill still works as expected 
- Make sure unlock on autofill works, shows the correct states on login and uses the possibly last auto-filled entry
- Changes to tabs in the same window should not create cpu-spikes (easiest to monitor)
- Changes to tabs in a different window should not create cpu-spikes (easiest to monitor)

If any further questions arise, feel free to reach out.

## Before you submit

- [X] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-03-31 04:42 UTC, eliykat requested changes
Nice work on this, this stuff gives me a headache.

To check my understanding, the basic idea here is "only react to updates in the active tab in the focused window" - which makes sense to me.

~One potential issue, what if a tab updates in the background (non-active tab or active tab in a non-focused window), then the user changes to it? The update will be ignored by Bitwarden.~ (snip) This will be fine, as you pointed out we already update when the tab or window changes.

2022-03-31 04:42 UTC, eliykat commented on src/background/tabs.background.ts
> +        const activeTab = await this.getActiveTabFromCurrentWindow();
You can just check `if (!tab.active) { return; }`

I don't really think we care about the `current` window, only the focused window, which we already check for above.

2022-03-31 04:42 UTC, eliykat commented on src/background/tabs.background.ts
> +        if (this.focusedWindowId > 0 && tab.windowId != this.focusedWindowId) {
It might be simpler to do
`chrome.windows.get(tab.windowId...` etc
And then check whether `window.focused` is true.

Then you could get rid of `this.focusedWindowId` (and the callback that sets it), which would be much easier to understand and maintain (and maybe more performant).

If you've got to wrap it in promises etc. then consider moving this call to `BrowserApi` to keep the logic here clean.

2022-03-31 04:42 UTC, eliykat commented on src/background/tabs.background.ts
>      if (!chrome.tabs) {
```suggestion
    if (!chrome.tabs || !chrome.windows) {
```

2022-03-31 04:42 UTC, eliykat commented on src/background/tabs.background.ts
>      if (!chrome.tabs) {
Assuming you need both apis for this logic to work correctly, which I think you do.

2022-03-31 04:47 UTC, eliykat commented
Also: in particular, QA should test behaviour when bouncing between different tabs/windows

2022-03-31 22:12 UTC, eliykat commented on src/background/tabs.background.ts
> +        if (this.focusedWindowId > 0 && tab.windowId != this.focusedWindowId) {
sorry, just realised you still need the `windows.onFocusChanged` callback to send the `windowChanged` message. But I still think it's better to just query the window directly here.

2022-03-31 22:14 UTC, eliykat commented on src/background/tabs.background.ts
> +        if (this.focusedWindowId > 0 && tab.windowId != this.focusedWindowId) {
Update: didn't realise that we have to listen to `window.onFocusChanged` anyway to send the message. In that case, if we're trying to eke out performance, maybe it's just better to leave this part as-is to avoid another chrome api call.

2022-04-06 16:17 UTC, djsmith85 commented on src/background/tabs.background.ts
>      if (!chrome.tabs) {
Correct, added it

2022-04-06 16:18 UTC, djsmith85 commented on src/background/tabs.background.ts
> +        if (this.focusedWindowId > 0 && tab.windowId != this.focusedWindowId) {
Keeping it in as commented

2022-04-06 16:24 UTC, djsmith85 commented
@eliykat Thank you for the review and your comments. I was able to simplifiy the changes and it's a lot easier to understand and we don't need additional chrome-api calls to achieve the same result.

Could you please test that Safari is still working as expected. I have verified Chrome and Firefox again after my last changes.

2022-04-07 06:08 UTC, eliykat commented
Changes look good, what's up with `package-lock.json` though?
I'll give it a quick whirl in Safari tomorrow.

2022-04-07 10:30 UTC, djsmith85 commented
I pulled in latest master and ran `npm i` as I usually do. I do that, as sometimes people, forget to commit the `package-lock.json` and the change looks okay for me. 🤷 

Thank you for giving this a spin in Safari.

2022-04-09 22:14 UTC, eliykat approved these changes
Quick test on Safari looks good, great work on this! I've added the hold label due to code freeze, but please remove it and merge once rc has been cut.

2022-04-11 10:00 UTC, merged