username generator
bitwarden/browser pull request #2468
Opened 2022-03-24 20:01 UTC by kspearrin

## Type of change

- [ ] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Add support for username generation.

Asana task: https://app.asana.com/0/1200578627114106/1201532987437763

## Code changes

- Bump jslib
- Add new translations
- Init username generation service
- Implement UI changes to accommodate username generation on the generator page (see screenshots below)
- Add generate username button to add/edit page

## Screenshots

![image](https://user-images.githubusercontent.com/1190944/160000135-9672b946-b48e-4d02-b3ae-d130831f7cf4.png)

![image](https://user-images.githubusercontent.com/1190944/160000090-976f1fad-d0c0-480b-95c6-3b15ac3c6d8a.png)

![image](https://user-images.githubusercontent.com/1190944/160000162-90233a82-cb37-4182-890d-0a04da6704f6.png)

## Testing requirements

1. Test existing password generation options from generator.
2. Test new username generation options from generator.
3. Test integration of username and password generation into item add/edit page.

## Before you submit

- [x] I have checked for **linting** errors (`npm run lint`) (required)
- [x] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-03-24 20:03 UTC, kspearrin commented on src/background/main.background.ts
> -    this.cryptoFunctionService = new WebCryptoFunctionService(window, this.platformUtilsService);
This was a fix from a change that came in from jslib that wasn't corrected yet. I think from @Hinton

2022-03-24 20:03 UTC, kspearrin commented on src/popup/components/pop-out.component.html
> +<ng-container *ngIf="show">
Looks to be a bug from over a year ago.

2022-03-24 20:04 UTC, Hinton commented on src/background/main.background.ts
> -    this.cryptoFunctionService = new WebCryptoFunctionService(window, this.platformUtilsService);
Correct.

2022-03-25 14:22 UTC, kspearrin commented
Not sure why, but I cannot seem to get jslib to not conflict here.

2022-03-27 18:08 UTC, Explosion-Scratch approved these changes

2022-03-28 15:00 UTC, kspearrin commented
@eliykat Care to review this one as well? Thanks!

2022-03-29 04:39 UTC, eliykat requested changes

2022-03-29 04:39 UTC, eliykat commented on src/popup/vault/add-edit.component.ts
> +      this.stateService.setAddEditCipherInfo({
I suggest this is moved to a private method rather than repeating it, e.g. `saveState()` (mostly because of the `collectionId` logic which takes it beyond a simple service call)

2022-03-29 04:39 UTC, eliykat commented on src/popup/generator/password-generator.component.ts
> +      this.cipherState.login.password = this.password;
I know this is the existing pattern, but it's strange that this isn't a call to `stateService.setAddEditCipherInfo`. I assume it works at the moment because `stateService` uses in memory storage for this value, but that seems like an assumption here (leaky abstraction). What do you think about changing it to use `stateService`?

2022-03-29 04:39 UTC, eliykat commented on src/popup/generator/password-generator.component.html
> +            [disabled]="showSelect"
It took me a moment to figure out why this was here, maybe rename `showSelect` to something more general/descriptive, e.g. `addEditCipher`.

2022-03-29 08:25 UTC, Hinton commented on package-lock.json
> -        "node-forge": "^0.10.0",
Please keep it, saves me opening a PR to ensure browser also gets `node-forge` bumped :).

2022-03-30 17:16 UTC, kspearrin commented on src/popup/generator/password-generator.component.html
> +            [disabled]="showSelect"
Not sure `addEditCipher` is more descriptive here. More like `comingFromAddEditCipher` which seems  a bit verbose. Regardless, I'll need to make this change in jslib and then update all clients thereafter. I suggest this being discussed in a follow up PR.

2022-03-30 17:16 UTC, kspearrin commented on src/popup/generator/password-generator.component.ts
> +      this.cipherState.login.password = this.password;
Done.

2022-03-30 17:16 UTC, kspearrin commented on src/popup/vault/add-edit.component.ts
> +      this.stateService.setAddEditCipherInfo({
Done.

2022-03-30 21:43 UTC, eliykat commented on src/popup/generator/password-generator.component.html
> +            [disabled]="showSelect"
I think `comingFromAddEditCipher` is good - it's clearer and is only used in a couple of places, so verbosity isn't that big of a deal. But we can leave it for now.

2022-03-30 21:43 UTC, eliykat approved these changes

2022-03-30 21:59 UTC, merged