[PS-74] Fix user authentication state checks
bitwarden/browser pull request #2481
Opened 2022-03-30 09:58 UTC by eliykat

## Type of change

- [x] Bug fix
- [ ] New feature development
- [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
- [ ] Build/deploy pipeline (DevOps)
- [ ] Other

## Objective

Client PR for https://github.com/bitwarden/jslib/pull/721
## Code changes

- **file.ext:** Description of what was changed and why

## Screenshots

## Testing requirements

## Before you submit

- [ ] I have checked for **linting** errors (`npm run lint`) (required)
- [ ] This change requires a **documentation update** (notify the documentation team)
- [ ] This change has particular **deployment requirements** (notify the DevOps team)

2022-04-29 12:44 UTC, djsmith85 requested changes
The work on jslib is great and simplifies the readability of the vault states.

Browser relies a lot on the authed/lock state. Please check that the previous behavior is unchanged.

2022-04-29 12:44 UTC, djsmith85 commented on src/background/notification.background.ts
> +    if ((await this.authService.getAuthStatus()) === AuthenticationStatus.Locked) {
Should also check for not authed and/or locked

2022-04-29 12:44 UTC, djsmith85 commented on src/background/webRequest.background.ts
> +    if ((await this.authService.getAuthStatus()) === AuthenticationStatus.Locked) {
Should error out, when not authed or locked as decrypting in either case would fail anyway

2022-04-29 12:44 UTC, djsmith85 commented on src/popup/accounts/lock.component.ts
> +        if ((await this.authService.getAuthStatus()) === AuthenticationStatus.Locked) {
Should also check for not authed

2022-04-29 12:44 UTC, djsmith85 commented on src/popup/accounts/sso.component.ts
> +      if ((await this.authService.getAuthStatus()) === AuthenticationStatus.Locked) {
Not sure here, but probably also a change in behavior we do not want

2022-04-29 23:40 UTC, eliykat commented on src/background/notification.background.ts
> +    if ((await this.authService.getAuthStatus()) === AuthenticationStatus.Locked) {
This had a separate `getIsAuthenticated` call earlier in the method to check for this - but I've refactored so that it calls `getAuthStatus()` once and uses the result in both checks. See the first couple of lines of the method.

2022-04-29 23:48 UTC, eliykat commented on src/popup/accounts/lock.component.ts
> +        if ((await this.authService.getAuthStatus()) === AuthenticationStatus.Locked) {
In this case I think it's more accurate. This is for biometric unlock and you can't unlock your vault if you're not logged in. I know that `isLocked()` returns `true` if logged out, but this code just won't work if the user is logged out, so it mustn't be executed in this case at the moment. (Presumably because `this.unlockBiometric` would be `false` because there is no biometric key stored)

2022-04-29 23:48 UTC, eliykat commented on src/popup/accounts/lock.component.ts
> +        if ((await this.authService.getAuthStatus()) === AuthenticationStatus.Locked) {
I have changed this to be single `if` statement though

2022-04-29 23:52 UTC, eliykat commented on src/popup/accounts/sso.component.ts
> +      if ((await this.authService.getAuthStatus()) === AuthenticationStatus.Locked) {
This method is only called after a successful login, so we are only checking if the vault is locked. But, I've changed this to be "if the vault is not unlocked", which better aligns with the comment (and addresses your feedback anyway).

2022-04-29 23:58 UTC, eliykat commented
Thank you for the thorough review - I'm definitely glad to be making all of these checks more explicit so that we don't have to think about this again in the future.

2022-04-30 15:17 UTC, djsmith85 approved these changes
@eliykat: This is looking good now 🚀 👍 

Could you please add some more info for QA to look out for.

2022-05-01 21:57 UTC, merged